services:
  backend:
    image: sanadcom-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./db:/code/db
  huey:
    image: sanadcom-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./db:/code/db
  frontend:
    image: sanadcom-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
