from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from core.models import AppliedControl, Asset, ComplianceAssessment, Framework, Perimeter, RiskAssessment
from iam.models import Folder, RoleAssignment

from .applied_control_suggestion_guardrails import (
    AppliedControlSuggestionDraftValidationError,
    validate_applied_control_suggestion_guardrails,
)
from .applied_control_suggestion_provider import (
    AppliedControlSuggestionProviderError,
    get_applied_control_suggestion_provider,
)
from .applied_control_suggestion_serializers import (
    AiAppliedControlSuggestionDraftSerializer,
    DEFAULT_USER_LOCALE,
    SCHEMA_VERSION,
)


class AiAppliedControlSuggestionService:
    def __init__(self, *, base_dir: str | None = None, provider=None):
        self.base_dir = base_dir or str(Path(__file__).resolve().parents[1])
        self.provider = provider

    def build_applied_control_suggestion_draft(self, request, request_data: dict[str, Any]) -> dict[str, Any]:
        normalized = _normalize_request_data(request_data)
        context = _resolve_context(request.user, normalized)
        resolved_assets = _resolve_asset_references(
            request.user,
            normalized["asset_references"],
            context["folder"],
        )
        provider = self.provider if self.provider is not None else get_applied_control_suggestion_provider()

        if provider is None:
            draft = build_applied_control_suggestion_fallback_draft(normalized, context, resolved_assets)
            _annotate_provider_mode(
                draft,
                provider_mode="provider_not_configured_fallback",
                parser_note="provider_mode: provider_not_configured_fallback",
                warning={
                    "code": "provider_not_configured_fallback",
                    "message": "No AI provider is configured; the advisory applied-control suggestion draft was generated by the deterministic fallback parser.",
                    "affected_fields": ["source_summary", "warnings"],
                    "needs_review": True,
                },
            )
        else:
            try:
                draft = provider.build_applied_control_suggestion_draft(normalized)
                _annotate_provider_mode(
                    draft,
                    provider_mode="configured_local_provider",
                    parser_note="provider_mode: configured_local_provider",
                )
            except AppliedControlSuggestionProviderError as exc:
                if not exc.allow_fallback:
                    raise
                draft = build_applied_control_suggestion_fallback_draft(
                    normalized,
                    context,
                    resolved_assets,
                )
                _annotate_provider_mode(
                    draft,
                    provider_mode="local_provider_error_fallback",
                    parser_note="provider_mode: local_provider_error_fallback",
                    warning={
                        "code": "local_provider_error_fallback",
                        "message": exc.detail,
                        "affected_fields": ["source_summary", "warnings"],
                        "needs_review": True,
                    },
                )

        _inject_context_summary(draft, normalized, context, resolved_assets)
        _apply_duplicate_detection(draft, request.user, context["folder"])
        _refresh_ambiguous_candidates(draft)
        _refresh_overall_confidence(draft)

        allowed_asset_ids = {str(item["instance"].id) for item in resolved_assets}
        validate_applied_control_suggestion_guardrails(
            draft,
            normalized,
            allowed_asset_ids=allowed_asset_ids,
            enforce_shape=False,
        )

        serializer = AiAppliedControlSuggestionDraftSerializer(data=draft)
        if not serializer.is_valid():
            raise AppliedControlSuggestionDraftValidationError(
                "ai_applied_control_suggestion_draft_validation_failed",
                "Generated advisory applied-control suggestion draft did not pass contract validation.",
                serializer.errors,
            )

        validated_draft = serializer.data
        validate_applied_control_suggestion_guardrails(
            validated_draft,
            normalized,
            allowed_asset_ids=allowed_asset_ids,
            enforce_shape=True,
        )
        return validated_draft


def build_applied_control_suggestion_draft(
    request,
    request_data: dict[str, Any],
    *,
    base_dir: str | None = None,
    provider=None,
) -> dict[str, Any]:
    service = AiAppliedControlSuggestionService(base_dir=base_dir, provider=provider)
    return service.build_applied_control_suggestion_draft(request, request_data)


def build_applied_control_suggestion_fallback_draft(
    request_data: dict[str, Any],
    context: dict[str, Any],
    resolved_assets: list[dict[str, Any]],
) -> dict[str, Any]:
    scenario_text = request_data.get("scenario_text", "")
    scope_summary = request_data.get("scope_summary", "")
    known_weaknesses = request_data.get("known_weaknesses") or []
    combined_text = "\n".join(filter(None, [scenario_text, scope_summary, *known_weaknesses]))
    locale = request_data.get("user_locale") or DEFAULT_USER_LOCALE

    warnings = [
        {
            "code": "best_effort_duplicate_detection",
            "message": "Duplicate detection is folder-scoped and best-effort because AppliedControl has no direct Perimeter field and many controls do not carry a reference id.",
            "affected_fields": ["duplicate_candidates", "candidate_applied_controls"],
            "needs_review": True,
        }
    ]
    if request_data.get("_user_locale_fallback_applied"):
        warnings.append(
            {
                "code": "user_locale_fallback",
                "message": "Unsupported locale was normalized to 'en' for the advisory applied-control suggestion draft.",
                "affected_fields": ["user_locale", "source_summary.detected_language"],
                "needs_review": True,
            }
        )

    source_refs = _build_default_source_refs(scenario_text, scope_summary, known_weaknesses)
    candidates = _build_candidate_applied_controls(combined_text, known_weaknesses, source_refs, resolved_assets)
    rejected = _build_rejected_candidates(combined_text)
    blocking_questions = _build_blocking_questions(candidates, bool(request_data.get("strict_mode", True)))

    return {
        "draft_type": "AiAppliedControlSuggestionDraft",
        "schema_version": SCHEMA_VERSION,
        "source_summary": {
            "detected_language": locale,
            "input_char_count": len(scenario_text),
            "strict_mode_applied": bool(request_data.get("strict_mode", True)),
            "scenario_excerpt": (scenario_text or scope_summary)[:160],
            "provider_mode": "provider_not_configured_fallback",
            "folder_id": context["folder"].id,
            "perimeter_id": getattr(context.get("perimeter"), "id", None),
            "compliance_assessment_id": getattr(context.get("compliance_assessment"), "id", None),
            "risk_assessment_id": getattr(context.get("risk_assessment"), "id", None),
            "selected_framework_id": getattr(context.get("framework"), "id", None),
            "asset_count": len(resolved_assets),
            "parser_notes": [
                "No GRC objects were created or updated.",
                "Fallback advisory applied-control draft generated from approved case context, approved assets, and scenario heuristics.",
            ],
        },
        "provider_mode": "provider_not_configured_fallback",
        "candidate_applied_controls": candidates,
        "duplicate_candidates": [],
        "ambiguous_candidates": [],
        "rejected_candidates": rejected,
        "warnings": warnings,
        "blocking_questions": blocking_questions,
        "needs_human_review": True,
        "overall_confidence": 0.0,
        "next_allowed_steps": [
            "review_control_candidates",
            "resolve_control_duplicates",
            "prepare_applied_control_commit_dry_run",
        ],
    }


def _normalize_request_data(request_data: dict[str, Any]) -> dict[str, Any]:
    normalized = dict(request_data)
    normalized["user_locale"] = normalized.get("user_locale") or DEFAULT_USER_LOCALE
    normalized["strict_mode"] = bool(normalized.get("strict_mode", True))
    normalized["known_weaknesses"] = list(normalized.get("known_weaknesses") or [])
    return normalized


def _annotate_provider_mode(
    draft: dict[str, Any],
    *,
    provider_mode: str,
    parser_note: str,
    warning: dict[str, Any] | None = None,
) -> None:
    source_summary = draft.setdefault("source_summary", {})
    parser_notes = source_summary.setdefault("parser_notes", [])
    if parser_note not in parser_notes:
        parser_notes.append(parser_note)
    source_summary["provider_mode"] = provider_mode
    draft["provider_mode"] = provider_mode
    if warning is not None:
        warnings = draft.setdefault("warnings", [])
        if not any(item.get("code") == warning["code"] for item in warnings if isinstance(item, dict)):
            warnings.append(warning)


def _resolve_context(user, request_data: dict[str, Any]) -> dict[str, Any]:
    reference = request_data.get("case_setup_reference") or {}
    folder = _get_object_or_error(Folder, reference["folder_id"], "case_setup_reference.folder_id")

    perimeter = None
    if reference.get("perimeter_id"):
        perimeter = _get_object_or_error(
            Perimeter,
            reference["perimeter_id"],
            "case_setup_reference.perimeter_id",
        )

    compliance_assessment = None
    if reference.get("compliance_assessment_id"):
        compliance_assessment = _get_object_or_error(
            ComplianceAssessment,
            reference["compliance_assessment_id"],
            "case_setup_reference.compliance_assessment_id",
        )

    risk_assessment = None
    if reference.get("risk_assessment_id"):
        risk_assessment = _get_object_or_error(
            RiskAssessment,
            reference["risk_assessment_id"],
            "case_setup_reference.risk_assessment_id",
        )

    framework = None
    framework_id = request_data.get("selected_framework_id") or reference.get("selected_framework_id")
    if framework_id:
        framework = _get_object_or_error(Framework, framework_id, "selected_framework_id")

    _assert_visible_to_user(user, folder, "case_setup_reference.folder_id")
    if perimeter is not None:
        _assert_visible_to_user(user, perimeter, "case_setup_reference.perimeter_id")
    if compliance_assessment is not None:
        _assert_visible_to_user(
            user,
            compliance_assessment,
            "case_setup_reference.compliance_assessment_id",
        )
    if risk_assessment is not None:
        _assert_visible_to_user(user, risk_assessment, "case_setup_reference.risk_assessment_id")
    if framework is not None:
        _assert_visible_to_user(user, framework, "selected_framework_id")

    errors = {}
    if perimeter is not None and perimeter.folder_id and str(perimeter.folder_id) != str(folder.id):
        errors["case_setup_reference"] = [
            "The selected Perimeter does not belong to case_setup_reference.folder_id."
        ]
    if compliance_assessment is not None:
        if compliance_assessment.folder_id and str(compliance_assessment.folder_id) != str(folder.id):
            errors["case_setup_reference"] = [
                "The selected ComplianceAssessment does not belong to case_setup_reference.folder_id."
            ]
        elif perimeter is not None and compliance_assessment.perimeter_id and str(compliance_assessment.perimeter_id) != str(perimeter.id):
            errors["case_setup_reference"] = [
                "The selected ComplianceAssessment does not belong to case_setup_reference.perimeter_id."
            ]
    if risk_assessment is not None:
        if risk_assessment.folder_id and str(risk_assessment.folder_id) != str(folder.id):
            errors["case_setup_reference"] = [
                "The selected RiskAssessment does not belong to case_setup_reference.folder_id."
            ]
        elif perimeter is not None and risk_assessment.perimeter_id and str(risk_assessment.perimeter_id) != str(perimeter.id):
            errors["case_setup_reference"] = [
                "The selected RiskAssessment does not belong to case_setup_reference.perimeter_id."
            ]
    if errors:
        raise AppliedControlSuggestionDraftValidationError(
            "ai_applied_control_suggestion_context_invalid",
            "The Step 4A request contains inconsistent case setup references.",
            errors,
        )

    return {
        "folder": folder,
        "perimeter": perimeter,
        "compliance_assessment": compliance_assessment,
        "risk_assessment": risk_assessment,
        "framework": framework,
    }


def _resolve_asset_references(user, asset_references: list[dict[str, Any]], folder: Folder) -> list[dict[str, Any]]:
    resolved_assets: list[dict[str, Any]] = []
    errors: dict[str, list[str]] = {}

    for index, reference in enumerate(asset_references):
        asset = Asset.objects.filter(id=reference["asset_id"]).select_related("folder", "asset_class").first()
        field_name = f"asset_references[{index}].asset_id"
        if asset is None:
            errors[field_name] = ["No Asset record was found for the supplied id."]
            continue

        _assert_visible_to_user(user, asset, field_name)

        if str(asset.folder_id) != str(folder.id):
            errors[field_name] = ["The referenced Asset does not belong to case_setup_reference.folder_id."]
            continue

        resolved_assets.append(
            {
                "instance": asset,
                "reference": reference,
            }
        )

    if errors:
        raise AppliedControlSuggestionDraftValidationError(
            "ai_applied_control_suggestion_asset_references_invalid",
            "The Step 4A request contains invalid asset references.",
            errors,
        )

    return resolved_assets


def _get_object_or_error(model_class, object_id, field_name: str):
    instance = model_class.objects.filter(id=object_id).first()
    if instance is None:
        raise AppliedControlSuggestionDraftValidationError(
            "ai_applied_control_suggestion_context_not_found",
            f"{field_name} could not be resolved.",
            {field_name: [f"No {model_class.__name__} record was found for the supplied id."]},
        )
    return instance


def _assert_visible_to_user(user, instance, field_name: str) -> None:
    if not getattr(user, "is_authenticated", False):
        return
    try:
        visible_ids = RoleAssignment.get_accessible_object_ids(
            folder=Folder.get_root_folder(),
            user=user,
            object_type=instance.__class__,
        )[0]
    except Exception:
        return
    if str(instance.id) not in {str(item_id) for item_id in visible_ids}:
        raise AppliedControlSuggestionDraftValidationError(
            "ai_applied_control_suggestion_permission_denied",
            f"{field_name} is not visible to the current user.",
            {field_name: ["You do not have permission to access this object."]},
        )


def _inject_context_summary(
    draft: dict[str, Any],
    request_data: dict[str, Any],
    context: dict[str, Any],
    resolved_assets: list[dict[str, Any]],
) -> None:
    source_summary = draft.setdefault("source_summary", {})
    source_summary.setdefault("detected_language", request_data.get("user_locale", DEFAULT_USER_LOCALE))
    source_summary.setdefault("input_char_count", len(request_data.get("scenario_text", "")))
    source_summary.setdefault("strict_mode_applied", bool(request_data.get("strict_mode", True)))
    source_summary.setdefault(
        "scenario_excerpt",
        (request_data.get("scenario_text") or request_data.get("scope_summary") or "")[:160],
    )
    source_summary["folder_id"] = context["folder"].id
    source_summary["perimeter_id"] = getattr(context.get("perimeter"), "id", None)
    source_summary["compliance_assessment_id"] = getattr(context.get("compliance_assessment"), "id", None)
    source_summary["risk_assessment_id"] = getattr(context.get("risk_assessment"), "id", None)
    source_summary["selected_framework_id"] = getattr(context.get("framework"), "id", None)
    source_summary["asset_count"] = len(resolved_assets)
    parser_notes = source_summary.setdefault("parser_notes", [])
    note = "Step 4A remained advisory-only and performed zero database writes."
    if note not in parser_notes:
        parser_notes.append(note)


def _build_default_source_refs(
    scenario_text: str,
    scope_summary: str,
    known_weaknesses: list[str],
) -> dict[str, dict[str, Any]]:
    refs: dict[str, dict[str, Any]] = {}
    if scenario_text:
        refs["scenario"] = _build_source_ref(scenario_text, scenario_text[:160], "T1")
    if scope_summary:
        refs["scope"] = _build_source_ref(scope_summary, scope_summary[:160], "T2")
    for index, weakness in enumerate(known_weaknesses, start=1):
        refs[f"weakness_{index}"] = _build_source_ref(weakness, weakness[:160], f"W{index}")
    return refs


def _build_candidate_applied_controls(
    combined_text: str,
    known_weaknesses: list[str],
    source_refs: dict[str, dict[str, Any]],
    resolved_assets: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    lowered = combined_text.lower()
    candidates: list[dict[str, Any]] = []
    safe_actions = [
        "accept_for_later_commit",
        "edit_before_commit",
        "reuse_existing_control",
        "reject",
        "mark_as_asset_candidate",
        "mark_as_evidence_candidate",
        "mark_as_vulnerability_candidate",
        "mark_as_risk_scenario_input",
        "defer",
    ]

    def add_candidate(
        *,
        temporary_id: str,
        proposed_name: str,
        proposed_description: str,
        proposed_control_type: str,
        proposed_control_category: str,
        proposed_status: str,
        proposed_implementation_state: str,
        linked_asset_ids: list[str],
        related_weaknesses: list[str],
        confidence: float,
        rationale: str,
        source_keys: list[str],
        ambiguity_flags: list[dict[str, str]] | None = None,
    ) -> None:
        candidates.append(
            {
                "temporary_id": temporary_id,
                "proposed_name": proposed_name,
                "proposed_description": proposed_description,
                "proposed_reference_id": None,
                "proposed_control_type": proposed_control_type,
                "proposed_control_category": proposed_control_category,
                "proposed_status": proposed_status,
                "proposed_implementation_state": proposed_implementation_state,
                "linked_asset_ids": linked_asset_ids,
                "linked_asset_temporary_ids": [
                    ref["reference"].get("source_temporary_id")
                    for ref in resolved_assets
                    if str(ref["instance"].id) in {str(item_id) for item_id in linked_asset_ids}
                    and ref["reference"].get("source_temporary_id")
                ],
                "related_weaknesses": related_weaknesses,
                "related_framework_requirements": [],
                "source_text_references": [source_refs[key] for key in source_keys if key in source_refs],
                "rationale": rationale,
                "confidence": confidence,
                "human_review_status": "pending_review",
                "ambiguity_flags": ambiguity_flags or [],
                "allowed_next_actions": list(safe_actions),
            }
        )

    remote_access_ids = _select_asset_ids(resolved_assets, "remote access", "vpn")
    privileged_account_ids = _select_asset_ids(resolved_assets, "privileged admin", "privileged account")
    user_account_ids = _select_asset_ids(resolved_assets, "user account", "production user")
    access_review_record_ids = _select_asset_ids(resolved_assets, "access review record")
    iam_system_ids = _select_asset_ids(resolved_assets, "identity provider", "iam system", "access management")
    policy_ids = _select_asset_ids(resolved_assets, "policy", "procedure")
    provisioning_record_ids = _select_asset_ids(resolved_assets, "provisioning record")
    core_banking_ids = _select_asset_ids(resolved_assets, "core banking")

    add_candidate(
        temporary_id="CTL-CAND-001",
        proposed_name="Username and Password Authentication for Existing Access",
        proposed_description="Maintain and govern username and password authentication for in-scope user access paths.",
        proposed_control_type="preventive",
        proposed_control_category="technical",
        proposed_status="active",
        proposed_implementation_state="existing",
        linked_asset_ids=_merge_asset_ids(core_banking_ids, iam_system_ids, user_account_ids),
        related_weaknesses=[],
        confidence=0.78,
        rationale="The scenario describes an existing user-access environment that already relies on baseline authentication, making the current authentication mechanism a valid existing control candidate.",
        source_keys=["scenario", "scope"],
    )

    if "mfa" in lowered or "multi-factor" in lowered or any("mfa" in item.lower() for item in known_weaknesses):
        add_candidate(
            temporary_id="CTL-CAND-002",
            proposed_name="Multi-Factor Authentication for Remote Access",
            proposed_description="Require multi-factor authentication for remote access to in-scope systems and identity services.",
            proposed_control_type="preventive",
            proposed_control_category="technical",
            proposed_status="to_do",
            proposed_implementation_state="planned",
            linked_asset_ids=_merge_asset_ids(remote_access_ids, iam_system_ids, core_banking_ids),
            related_weaknesses=[item for item in known_weaknesses if "mfa" in item.lower() or "remote access" in item.lower()],
            confidence=0.93,
            rationale="The scenario explicitly identifies missing MFA for remote access, which maps to a planned technical applied control rather than a final compliance decision.",
            source_keys=["scenario", "weakness_1"],
        )

    if "pam" in lowered or "privileged" in lowered:
        add_candidate(
            temporary_id="CTL-CAND-003",
            proposed_name="Privileged Access Management for Administrator Accounts",
            proposed_description="Implement privileged access management controls for privileged administrative accounts and sensitive identity operations.",
            proposed_control_type="preventive",
            proposed_control_category="technical",
            proposed_status="to_do",
            proposed_implementation_state="planned",
            linked_asset_ids=_merge_asset_ids(privileged_account_ids, iam_system_ids, core_banking_ids),
            related_weaknesses=[item for item in known_weaknesses if "pam" in item.lower() or "privileged" in item.lower()],
            confidence=0.9,
            rationale="The scenario identifies a PAM gap affecting privileged admin accounts, which maps to a planned applied control candidate.",
            source_keys=["scenario", "weakness_2"],
            ambiguity_flags=[
                {
                    "code": "pam_process_or_system_review",
                    "message": "PAM can refer to a technical platform, an operating process, or both; review the control scope and linked assets before any future commit.",
                }
            ],
        )

    add_candidate(
        temporary_id="CTL-CAND-004",
        proposed_name="Periodic User Access Review",
        proposed_description="Perform documented periodic reviews of user and privileged access for the approved scope.",
        proposed_control_type="detective",
        proposed_control_category="process",
        proposed_status="to_do",
        proposed_implementation_state="planned",
        linked_asset_ids=_merge_asset_ids(user_account_ids, privileged_account_ids, access_review_record_ids),
        related_weaknesses=[
            item
            for item in known_weaknesses
            if "review" in item.lower() or "documented" in item.lower()
        ],
        confidence=0.95,
        rationale="The scenario explicitly describes missing periodic access reviews and lack of formal documented review activity, which strongly maps to a process control candidate.",
        source_keys=["scenario", "weakness_3"],
    )

    add_candidate(
        temporary_id="CTL-CAND-005",
        proposed_name="Formal User Provisioning and Deprovisioning Process",
        proposed_description="Operate a formal joiner, mover, leaver provisioning and deprovisioning process for in-scope identities.",
        proposed_control_type="preventive",
        proposed_control_category="process",
        proposed_status="to_do",
        proposed_implementation_state="planned",
        linked_asset_ids=_merge_asset_ids(provisioning_record_ids, iam_system_ids, user_account_ids),
        related_weaknesses=[item for item in known_weaknesses if "documented" in item.lower()],
        confidence=0.87,
        rationale="The scenario concerns user access management and weak formal governance, making a provisioning and deprovisioning process a likely planned control candidate.",
        source_keys=["scenario", "scope"],
    )

    add_candidate(
        temporary_id="CTL-CAND-006",
        proposed_name="Access Review Records Retention Control",
        proposed_description="Retain access review records and evidence for periodic review activities in accordance with policy expectations.",
        proposed_control_type="governance",
        proposed_control_category="procedure",
        proposed_status="to_do",
        proposed_implementation_state="planned",
        linked_asset_ids=_merge_asset_ids(access_review_record_ids),
        related_weaknesses=[item for item in known_weaknesses if "record" in item.lower() or "review" in item.lower()],
        confidence=0.72,
        rationale="The scenario mentions missing access review records, which often implies a retention or record-governance control rather than the records themselves as the control.",
        source_keys=["scenario", "weakness_3"],
        ambiguity_flags=[
            {
                "code": "evidence_or_control_boundary",
                "message": "Access review records are often evidence or records rather than the control itself; review whether this candidate should remain a control or move to future evidence handling.",
            }
        ],
    )

    add_candidate(
        temporary_id="CTL-CAND-007",
        proposed_name="Remote Access Logging and Monitoring Control",
        proposed_description="Log and monitor remote access activity for in-scope systems and identity services.",
        proposed_control_type="detective",
        proposed_control_category="technical",
        proposed_status="to_do",
        proposed_implementation_state="planned",
        linked_asset_ids=_merge_asset_ids(remote_access_ids, iam_system_ids),
        related_weaknesses=[item for item in known_weaknesses if "remote access" in item.lower()],
        confidence=0.84,
        rationale="Remote access weaknesses in the scenario make logging and monitoring a reasonable detective control candidate tied to the approved remote access assets.",
        source_keys=["scenario", "weakness_1"],
    )

    if policy_ids or "policy" in lowered or "procedure" in lowered or "documented" in lowered:
        add_candidate(
            temporary_id="CTL-CAND-008",
            proposed_name="IAM Policies and Procedures Maintenance Control",
            proposed_description="Maintain and periodically review IAM policies and procedures for user lifecycle, access review, and privileged access governance.",
            proposed_control_type="governance",
            proposed_control_category="policy",
            proposed_status="to_do",
            proposed_implementation_state="planned",
            linked_asset_ids=_merge_asset_ids(policy_ids, iam_system_ids),
            related_weaknesses=[item for item in known_weaknesses if "documented" in item.lower()],
            confidence=0.8,
            rationale="The scenario highlights missing formal review and documentation, which strongly suggests a governance control around IAM policies and procedures.",
            source_keys=["scenario", "scope"],
        )

    return candidates


def _build_rejected_candidates(combined_text: str) -> list[dict[str, Any]]:
    lowered = combined_text.lower()
    rejected: list[dict[str, Any]] = []
    if "no mfa" in lowered:
        rejected.append(
            {
                "source_label": "No MFA for remote access",
                "recommended_reclassification": "vulnerability_candidate",
                "reason": "The phrase describes a missing safeguard and should not itself be treated as the control record.",
                "confidence": 0.9,
            }
        )
    if "no pam" in lowered:
        rejected.append(
            {
                "source_label": "No PAM for privileged admin accounts",
                "recommended_reclassification": "vulnerability_candidate",
                "reason": "The phrase describes a missing privileged-access safeguard and should not itself be treated as the control record.",
                "confidence": 0.88,
            }
        )
    if "access review records" in lowered:
        rejected.append(
            {
                "source_label": "Access Review Records",
                "recommended_reclassification": "evidence_candidate",
                "reason": "The records themselves are often evidence or governed information records rather than the control activity.",
                "confidence": 0.79,
            }
        )
    return rejected


def _build_blocking_questions(
    candidates: list[dict[str, Any]],
    strict_mode: bool,
) -> list[dict[str, Any]]:
    questions: list[dict[str, Any]] = []
    if any(item.get("ambiguity_flags") for item in candidates):
        questions.append(
            {
                "question_id": "control-classification-review",
                "question_text": "Which ambiguous candidate controls should remain controls versus be reclassified as assets, evidence, vulnerabilities, or risk-scenario inputs?",
                "reason": "Several candidates describe records, governance materials, or mixed process-versus-tool concepts that cannot be safely forced into AppliedControl creation without human review.",
                "affected_fields": ["candidate_applied_controls", "ambiguous_candidates"],
                "severity": "blocking",
            }
        )
    if strict_mode and all(item.get("confidence", 0.0) < 0.75 for item in candidates):
        questions.append(
            {
                "question_id": "low-confidence-control-scope",
                "question_text": "Which concrete safeguards are definitely in scope for the approved case and approved asset set?",
                "reason": "Strict mode prevents low-confidence control suggestions from being treated as implementation-ready without clarification.",
                "affected_fields": ["candidate_applied_controls"],
                "severity": "blocking",
            }
        )
    return questions


def _build_source_ref(text: str, excerpt: str, ref_id: str) -> dict[str, Any]:
    if excerpt and text:
        lowered_text = text.lower()
        lowered_excerpt = excerpt.lower()
        char_start = lowered_text.find(lowered_excerpt)
        if char_start < 0:
            char_start = 0
        char_end = min(len(text), char_start + len(excerpt))
    else:
        char_start = 0
        char_end = 0
    return {
        "ref_id": ref_id,
        "excerpt": excerpt,
        "char_start": char_start,
        "char_end": char_end,
    }


def _apply_duplicate_detection(draft: dict[str, Any], user, folder: Folder) -> None:
    accessible_ids = _get_visible_applied_control_ids(user)
    folder_controls = AppliedControl.objects.filter(folder=folder)
    if accessible_ids is not None:
        folder_controls = folder_controls.filter(id__in=accessible_ids)
    folder_controls = list(folder_controls.select_related("folder").prefetch_related("assets"))

    duplicate_candidates: list[dict[str, Any]] = []
    for candidate in draft.get("candidate_applied_controls", []):
        matches = _find_candidate_matches(candidate, folder_controls)
        if matches:
            duplicate_candidates.append(
                {
                    "temporary_id": candidate["temporary_id"],
                    "proposed_name": candidate["proposed_name"],
                    "matches": matches,
                    "recommended_human_action": "review_reuse_or_rename",
                }
            )
    draft["duplicate_candidates"] = duplicate_candidates


def _get_visible_applied_control_ids(user):
    if not getattr(user, "is_authenticated", False):
        return None
    try:
        return RoleAssignment.get_accessible_object_ids(
            folder=Folder.get_root_folder(),
            user=user,
            object_type=AppliedControl,
        )[0]
    except Exception:
        return None


def _find_candidate_matches(
    candidate: dict[str, Any],
    folder_controls: list[AppliedControl],
) -> list[dict[str, Any]]:
    proposed_name = str(candidate.get("proposed_name") or "").strip()
    proposed_ref = str(candidate.get("proposed_reference_id") or "").strip()
    normalized_name = _normalize_token(proposed_name)
    candidate_asset_ids = {str(asset_id) for asset_id in candidate.get("linked_asset_ids") or []}
    matches_by_id: dict[str, dict[str, Any]] = {}

    for control in folder_controls:
        match_type = None
        match_score = 0.0
        if proposed_name and control.name == proposed_name:
            match_type = "exact_name_same_folder"
            match_score = 0.99
        elif proposed_name and _normalize_token(control.name) == normalized_name:
            match_type = "normalized_name_same_folder"
            match_score = 0.9
        elif proposed_ref and control.ref_id and control.ref_id.strip().lower() == proposed_ref.lower():
            match_type = "reference_id_same_folder"
            match_score = 0.97
        elif candidate_asset_ids:
            linked_asset_ids = {str(asset_id) for asset_id in control.assets.values_list("id", flat=True)}
            if linked_asset_ids and linked_asset_ids == candidate_asset_ids:
                match_type = "same_linked_assets_same_folder"
                match_score = 0.76

        if match_type:
            existing_match = matches_by_id.get(str(control.id))
            if existing_match and existing_match["match_score"] >= match_score:
                continue
            matches_by_id[str(control.id)] = {
                "existing_applied_control_id": control.id,
                "existing_name": control.name,
                "existing_ref_id": control.ref_id or None,
                "existing_category": control.category or None,
                "existing_status": control.status or None,
                "linked_asset_ids": list(control.assets.values_list("id", flat=True)),
                "folder_id": control.folder_id,
                "folder_name": control.folder.name,
                "match_type": match_type,
                "match_score": match_score,
                "scope_relevance": "high",
                "warning": "Potential duplicate within the selected folder.",
            }

    return list(matches_by_id.values())


def _normalize_token(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", value.lower())


def _refresh_ambiguous_candidates(draft: dict[str, Any]) -> None:
    ambiguous_candidates = []
    for candidate in draft.get("candidate_applied_controls", []):
        ambiguity_flags = candidate.get("ambiguity_flags") or []
        if ambiguity_flags:
            ambiguous_candidates.append(
                {
                    "temporary_id": candidate["temporary_id"],
                    "proposed_name": candidate["proposed_name"],
                    "ambiguity_flags": ambiguity_flags,
                    "recommended_actions": [
                        "accept_for_later_commit",
                        "edit_before_commit",
                        "mark_as_asset_candidate",
                        "mark_as_evidence_candidate",
                        "mark_as_vulnerability_candidate",
                        "mark_as_risk_scenario_input",
                        "reject",
                        "defer",
                    ],
                }
            )
    draft["ambiguous_candidates"] = ambiguous_candidates


def _refresh_overall_confidence(draft: dict[str, Any]) -> None:
    candidate_controls = draft.get("candidate_applied_controls") or []
    if candidate_controls:
        avg = sum(item.get("confidence", 0.0) for item in candidate_controls) / len(candidate_controls)
    else:
        avg = 0.0
    draft["overall_confidence"] = round(avg, 2)


def _select_asset_ids(resolved_assets: list[dict[str, Any]], *phrases: str) -> list[str]:
    matched: list[str] = []
    lowered_phrases = [phrase.lower() for phrase in phrases if phrase]
    for item in resolved_assets:
        asset = item["instance"]
        lowered_name = asset.name.lower()
        if any(phrase in lowered_name for phrase in lowered_phrases):
            matched.append(str(asset.id))
    return matched


def _merge_asset_ids(*collections: list[str]) -> list[str]:
    merged: list[str] = []
    for collection in collections:
        for item in collection:
            if item not in merged:
                merged.append(item)
    return merged