from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from core.models import Asset, ComplianceAssessment, Framework, Perimeter, RiskAssessment
from iam.models import Folder, RoleAssignment

from .asset_suggestion_guardrails import AssetSuggestionDraftValidationError, validate_asset_suggestion_guardrails
from .asset_suggestion_provider import AssetSuggestionProviderError, get_asset_suggestion_provider
from .asset_suggestion_serializers import AiAssetSuggestionDraftSerializer, DEFAULT_USER_LOCALE, SCHEMA_VERSION


class AiAssetSuggestionService:
    def __init__(self, *, base_dir: str | None = None, provider=None):
        self.base_dir = base_dir or str(Path(__file__).resolve().parents[1])
        self.provider = provider

    def build_asset_suggestion_draft(self, request, request_data: dict[str, Any]) -> dict[str, Any]:
        normalized = _normalize_request_data(request_data)
        context = _resolve_context(request.user, normalized)
        provider = self.provider if self.provider is not None else get_asset_suggestion_provider()

        if provider is None:
            draft = build_asset_suggestion_fallback_draft(normalized, context)
            _annotate_provider_mode(
                draft,
                provider_mode="provider_not_configured_fallback",
                parser_note="provider_mode: provider_not_configured_fallback",
                warning={
                    "code": "provider_not_configured_fallback",
                    "message": "No AI provider is configured; the advisory asset suggestion draft was generated by the deterministic fallback parser.",
                    "affected_fields": ["source_summary", "warnings"],
                    "needs_review": True,
                },
            )
        else:
            try:
                draft = provider.build_asset_suggestion_draft(normalized)
                _annotate_provider_mode(
                    draft,
                    provider_mode="configured_local_provider",
                    parser_note="provider_mode: configured_local_provider",
                )
            except AssetSuggestionProviderError as exc:
                if not exc.allow_fallback:
                    raise
                draft = build_asset_suggestion_fallback_draft(normalized, context)
                _annotate_provider_mode(
                    draft,
                    provider_mode="local_provider_error_fallback",
                    parser_note="provider_mode: local_provider_error_fallback",
                    warning={
                        "code": "local_provider_error_fallback",
                        "message": exc.detail,
                        "affected_fields": ["source_summary", "warnings"],
                        "needs_review": True,
                    },
                )

        _inject_context_summary(draft, normalized, context)
        _apply_duplicate_detection(draft, request.user, context["folder"])
        _refresh_ambiguous_candidates(draft)
        _refresh_overall_confidence(draft)
        _ensure_low_confidence_blocking_question(draft, normalized)

        validate_asset_suggestion_guardrails(draft, normalized, enforce_shape=False)

        serializer = AiAssetSuggestionDraftSerializer(data=draft)
        if not serializer.is_valid():
            raise AssetSuggestionDraftValidationError(
                "ai_asset_suggestion_draft_validation_failed",
                "Generated advisory asset suggestion draft did not pass contract validation.",
                serializer.errors,
            )

        validated_draft = serializer.data
        validate_asset_suggestion_guardrails(validated_draft, normalized)
        return validated_draft


def build_asset_suggestion_draft(
    request,
    request_data: dict[str, Any],
    *,
    base_dir: str | None = None,
    provider=None,
) -> dict[str, Any]:
    service = AiAssetSuggestionService(base_dir=base_dir, provider=provider)
    return service.build_asset_suggestion_draft(request, request_data)


def build_asset_suggestion_fallback_draft(
    request_data: dict[str, Any],
    context: dict[str, Any],
) -> dict[str, Any]:
    scenario_text = request_data.get("scenario_text", "")
    scope_summary = request_data.get("scope_summary", "")
    known_weaknesses = request_data.get("known_weaknesses") or []
    combined_text = "\n".join(filter(None, [scenario_text, scope_summary, *known_weaknesses]))
    locale = request_data.get("user_locale") or DEFAULT_USER_LOCALE

    warnings = [
        {
            "code": "best_effort_duplicate_detection",
            "message": "Duplicate detection is folder-scoped and best-effort because Asset has no direct Perimeter field and many assets do not carry a reference id.",
            "affected_fields": ["duplicate_candidates", "candidate_assets"],
            "needs_review": True,
        }
    ]
    if request_data.get("_user_locale_fallback_applied"):
        warnings.append(
            {
                "code": "user_locale_fallback",
                "message": "Unsupported locale was normalized to 'en' for the advisory asset suggestion draft.",
                "affected_fields": ["user_locale", "source_summary.detected_language"],
                "needs_review": True,
            }
        )

    source_refs = _build_default_source_refs(scenario_text, scope_summary, known_weaknesses)
    candidates = _build_candidate_assets(combined_text, source_refs, context)
    rejected = _build_rejected_candidates(combined_text)
    blocking_questions = _build_blocking_questions(candidates, request_data.get("strict_mode", True))

    return {
        "draft_type": "AiAssetSuggestionDraft",
        "schema_version": SCHEMA_VERSION,
        "source_summary": {
            "detected_language": locale,
            "input_char_count": len(scenario_text),
            "strict_mode_applied": bool(request_data.get("strict_mode", True)),
            "scenario_excerpt": (scenario_text or scope_summary)[:160],
            "provider_mode": "provider_not_configured_fallback",
            "folder_id": context["folder"].id,
            "perimeter_id": context["perimeter"].id,
            "compliance_assessment_id": context["compliance_assessment"].id,
            "risk_assessment_id": getattr(context.get("risk_assessment"), "id", None),
            "parser_notes": [
                "No GRC objects were created or updated.",
                "Fallback advisory asset draft generated from approved case context and scenario heuristics.",
            ],
        },
        "provider_mode": "provider_not_configured_fallback",
        "candidate_assets": candidates,
        "duplicate_candidates": [],
        "ambiguous_candidates": [],
        "rejected_candidates": rejected,
        "warnings": warnings,
        "blocking_questions": blocking_questions,
        "needs_human_review": True,
        "overall_confidence": 0.0,
        "next_allowed_steps": [
            "review_candidate_assets",
            "resolve_duplicates",
            "prepare_asset_commit_dry_run",
        ],
    }


def _normalize_request_data(request_data: dict[str, Any]) -> dict[str, Any]:
    normalized = dict(request_data)
    normalized["user_locale"] = normalized.get("user_locale") or DEFAULT_USER_LOCALE
    normalized["strict_mode"] = bool(normalized.get("strict_mode", True))
    normalized["known_weaknesses"] = list(normalized.get("known_weaknesses") or [])
    return normalized


def _annotate_provider_mode(
    draft: dict[str, Any],
    *,
    provider_mode: str,
    parser_note: str,
    warning: dict[str, Any] | None = None,
) -> None:
    source_summary = draft.setdefault("source_summary", {})
    parser_notes = source_summary.setdefault("parser_notes", [])
    if parser_note not in parser_notes:
        parser_notes.append(parser_note)
    source_summary["provider_mode"] = provider_mode
    draft["provider_mode"] = provider_mode
    if warning is not None:
        warnings = draft.setdefault("warnings", [])
        if not any(item.get("code") == warning["code"] for item in warnings if isinstance(item, dict)):
            warnings.append(warning)


def _resolve_context(user, request_data: dict[str, Any]) -> dict[str, Any]:
    folder = _get_object_or_error(Folder, request_data["folder_id"], "folder_id")
    perimeter = _get_object_or_error(Perimeter, request_data["perimeter_id"], "perimeter_id")
    compliance_assessment = _get_object_or_error(
        ComplianceAssessment,
        request_data["compliance_assessment_id"],
        "compliance_assessment_id",
    )
    risk_assessment = None
    if request_data.get("risk_assessment_id"):
        risk_assessment = _get_object_or_error(
            RiskAssessment,
            request_data["risk_assessment_id"],
            "risk_assessment_id",
        )
    framework = None
    if request_data.get("selected_framework_id"):
        framework = _get_object_or_error(
            Framework,
            request_data["selected_framework_id"],
            "selected_framework_id",
        )

    _assert_visible_to_user(user, folder, "folder_id")
    _assert_visible_to_user(user, perimeter, "perimeter_id")
    _assert_visible_to_user(user, compliance_assessment, "compliance_assessment_id")
    if risk_assessment is not None:
        _assert_visible_to_user(user, risk_assessment, "risk_assessment_id")
    if framework is not None:
        _assert_visible_to_user(user, framework, "selected_framework_id")

    errors = {}
    if perimeter.folder_id and str(perimeter.folder_id) != str(folder.id):
        errors["perimeter_id"] = ["The selected Perimeter does not belong to folder_id."]
    if compliance_assessment.folder_id and str(compliance_assessment.folder_id) != str(folder.id):
        errors["compliance_assessment_id"] = [
            "The selected ComplianceAssessment does not belong to folder_id."
        ]
    if compliance_assessment.perimeter_id and str(compliance_assessment.perimeter_id) != str(perimeter.id):
        errors["compliance_assessment_id"] = [
            "The selected ComplianceAssessment does not belong to perimeter_id."
        ]
    if risk_assessment is not None:
        if risk_assessment.folder_id and str(risk_assessment.folder_id) != str(folder.id):
            errors["risk_assessment_id"] = [
                "The selected RiskAssessment does not belong to folder_id."
            ]
        elif risk_assessment.perimeter_id and str(risk_assessment.perimeter_id) != str(perimeter.id):
            errors["risk_assessment_id"] = [
                "The selected RiskAssessment does not belong to perimeter_id."
            ]
    if errors:
        raise AssetSuggestionDraftValidationError(
            "ai_asset_suggestion_context_invalid",
            "The Step 3A request contains inconsistent case setup references.",
            errors,
        )

    return {
        "folder": folder,
        "perimeter": perimeter,
        "compliance_assessment": compliance_assessment,
        "risk_assessment": risk_assessment,
        "framework": framework,
    }


def _get_object_or_error(model_class, object_id, field_name: str):
    instance = model_class.objects.filter(id=object_id).first()
    if instance is None:
        raise AssetSuggestionDraftValidationError(
            "ai_asset_suggestion_context_not_found",
            f"{field_name} could not be resolved.",
            {field_name: [f"No {model_class.__name__} record was found for the supplied id."]},
        )
    return instance


def _assert_visible_to_user(user, instance, field_name: str) -> None:
    if not getattr(user, "is_authenticated", False):
        return
    try:
        visible_ids = RoleAssignment.get_accessible_object_ids(
            folder=Folder.get_root_folder(),
            user=user,
            object_type=instance.__class__,
        )[0]
    except Exception:
        return
    if str(instance.id) not in {str(item_id) for item_id in visible_ids}:
        raise AssetSuggestionDraftValidationError(
            "ai_asset_suggestion_permission_denied",
            f"{field_name} is not visible to the current user.",
            {field_name: ["You do not have permission to access this object."]},
        )


def _inject_context_summary(
    draft: dict[str, Any],
    request_data: dict[str, Any],
    context: dict[str, Any],
) -> None:
    source_summary = draft.setdefault("source_summary", {})
    source_summary.setdefault("detected_language", request_data.get("user_locale", DEFAULT_USER_LOCALE))
    source_summary.setdefault("input_char_count", len(request_data.get("scenario_text", "")))
    source_summary.setdefault("strict_mode_applied", bool(request_data.get("strict_mode", True)))
    source_summary.setdefault(
        "scenario_excerpt",
        (request_data.get("scenario_text") or request_data.get("scope_summary") or "")[:160],
    )
    source_summary["folder_id"] = context["folder"].id
    source_summary["perimeter_id"] = context["perimeter"].id
    source_summary["compliance_assessment_id"] = context["compliance_assessment"].id
    source_summary["risk_assessment_id"] = getattr(context.get("risk_assessment"), "id", None)
    parser_notes = source_summary.setdefault("parser_notes", [])
    note = "Step 3A remained advisory-only and performed zero database writes."
    if note not in parser_notes:
        parser_notes.append(note)


def _build_default_source_refs(
    scenario_text: str,
    scope_summary: str,
    known_weaknesses: list[str],
) -> dict[str, dict[str, Any]]:
    refs: dict[str, dict[str, Any]] = {}
    if scenario_text:
        refs["scenario"] = _build_source_ref(scenario_text, scenario_text[:160], "T1")
    if scope_summary:
        refs["scope"] = _build_source_ref(scope_summary, scope_summary[:160], "T2")
    if known_weaknesses:
        refs["weaknesses"] = _build_source_ref(
            "\n".join(known_weaknesses),
            known_weaknesses[0][:160],
            "T3",
        )
    return refs


def _build_candidate_assets(
    combined_text: str,
    source_refs: dict[str, dict[str, Any]],
    context: dict[str, Any],
) -> list[dict[str, Any]]:
    lowered = combined_text.lower()
    candidates: list[dict[str, Any]] = []
    safe_actions = [
        "accept_for_later_commit",
        "edit_before_commit",
        "reuse_existing_asset",
        "reject",
        "mark_as_evidence_candidate",
        "mark_as_control_candidate",
        "mark_as_vulnerability_candidate",
        "defer",
    ]

    def add_candidate(
        *,
        temporary_id: str,
        proposed_name: str,
        proposed_description: str,
        proposed_asset_type: str,
        proposed_asset_category: str,
        criticality: str,
        confidence: float,
        rationale: str,
        source_keys: list[str],
        ambiguity_flags: list[dict[str, str]] | None = None,
    ) -> None:
        candidates.append(
            {
                "temporary_id": temporary_id,
                "proposed_name": proposed_name,
                "proposed_description": proposed_description,
                "proposed_reference_id": None,
                "proposed_asset_type": {
                    "value": proposed_asset_type,
                    "label": "Primary" if proposed_asset_type == "PR" else "Support",
                },
                "proposed_asset_category": proposed_asset_category,
                "criticality": {
                    "value": criticality,
                    "is_platform_writable": False,
                    "mapping_note": "Criticality is advisory only in Step 3A.",
                },
                "folder_id": context["folder"].id,
                "perimeter_id": context["perimeter"].id,
                "compliance_assessment_id": context["compliance_assessment"].id,
                "source_text_references": [source_refs[key] for key in source_keys if key in source_refs],
                "rationale": rationale,
                "confidence": confidence,
                "human_review_status": "pending_review",
                "ambiguity_flags": ambiguity_flags or [],
                "allowed_next_actions": list(safe_actions),
            }
        )

    if any(token in lowered for token in ("core banking", "banking platform", "core banking platform")):
        add_candidate(
            temporary_id="AST-CAND-001",
            proposed_name="Core Banking Application",
            proposed_description="Primary business application in scope for the user access management review.",
            proposed_asset_type="PR",
            proposed_asset_category="application",
            criticality="high",
            confidence=0.94,
            rationale="The scenario explicitly identifies the core banking platform as the central scope of the assessment.",
            source_keys=["scenario", "scope"],
        )
    if any(token in lowered for token in ("user access", "user accounts", "access review")):
        add_candidate(
            temporary_id="AST-CAND-002",
            proposed_name="Production User Accounts",
            proposed_description="Account population subject to the user access management scope.",
            proposed_asset_type="SP",
            proposed_asset_category="account_population",
            criticality="high",
            confidence=0.8,
            rationale="The scenario focuses on user access governance, which often requires the managed user account estate to be reviewed as an asset candidate.",
            source_keys=["scenario", "weaknesses"],
            ambiguity_flags=[
                {
                    "code": "account_population_requires_review",
                    "message": "Account populations may be modeled as scoped assets or as identity-control surfaces depending on local governance practice.",
                }
            ],
        )
        add_candidate(
            temporary_id="AST-CAND-003",
            proposed_name="Privileged Admin Accounts",
            proposed_description="Privileged account population associated with the in-scope administrative access surface.",
            proposed_asset_type="SP",
            proposed_asset_category="privileged_accounts",
            criticality="high",
            confidence=0.83,
            rationale="The scenario explicitly calls out privileged admin account weaknesses and PAM gaps, making the privileged account estate a likely review target.",
            source_keys=["scenario", "weaknesses"],
            ambiguity_flags=[
                {
                    "code": "privileged_account_surface_requires_review",
                    "message": "This may represent a governed asset, a control surface, or both and must be reviewed by a human.",
                }
            ],
        )
    if any(token in lowered for token in ("access review", "review records")):
        add_candidate(
            temporary_id="AST-CAND-004",
            proposed_name="Access Review Records",
            proposed_description="Record set for periodic access reviews and approval evidence in the IAM scope.",
            proposed_asset_type="SP",
            proposed_asset_category="records",
            criticality="medium",
            confidence=0.68,
            rationale="The scenario calls out the absence of periodic access review records, which may indicate a governed record asset or future evidence source.",
            source_keys=["weaknesses", "scenario"],
            ambiguity_flags=[
                {
                    "code": "asset_or_evidence",
                    "message": "Access review records may be modeled as an information asset or as evidence and must not be forced into asset creation without review.",
                }
            ],
        )
    if any(token in lowered for token in ("remote access", "vpn")):
        add_candidate(
            temporary_id="AST-CAND-005",
            proposed_name="Remote Access / VPN Service",
            proposed_description="Remote access service supporting in-scope user access paths.",
            proposed_asset_type="SP",
            proposed_asset_category="service",
            criticality="high",
            confidence=0.9,
            rationale="Remote access is explicitly mentioned in the weaknesses and typically maps to a supporting service asset.",
            source_keys=["weaknesses", "scenario"],
        )
    if any(
        token in lowered
        for token in (
            "iam",
            "identity provider",
            "identity",
            "user access management",
            "access management",
        )
    ):
        add_candidate(
            temporary_id="AST-CAND-006",
            proposed_name="Identity Provider / IAM System",
            proposed_description="Identity and access management platform or service supporting the scoped access review.",
            proposed_asset_type="SP",
            proposed_asset_category="iam_system",
            criticality="high",
            confidence=0.92,
            rationale="The scenario explicitly references IAM scope and access management weaknesses, making the IAM platform a strong supporting asset candidate.",
            source_keys=["scenario", "scope"],
        )
        add_candidate(
            temporary_id="AST-CAND-007",
            proposed_name="IAM Policies and Procedures",
            proposed_description="Documentation set governing user access, account lifecycle, and access review expectations.",
            proposed_asset_type="SP",
            proposed_asset_category="documentation",
            criticality="medium",
            confidence=0.62,
            rationale="The scenario highlights missing formal review and documentation, which may indicate a documentation asset candidate or future control or evidence material.",
            source_keys=["scenario", "weaknesses"],
            ambiguity_flags=[
                {
                    "code": "asset_or_control_or_evidence",
                    "message": "Policy and procedure material may be modeled as documentation, evidence, or control support rather than a standalone asset.",
                }
            ],
        )
        add_candidate(
            temporary_id="AST-CAND-008",
            proposed_name="User Provisioning Records",
            proposed_description="Record set capturing account provisioning, change, and deprovisioning actions.",
            proposed_asset_type="SP",
            proposed_asset_category="records",
            criticality="medium",
            confidence=0.66,
            rationale="Provisioning records are relevant to IAM reviews and may represent either a governed record asset or future evidence.",
            source_keys=["scenario", "weaknesses"],
            ambiguity_flags=[
                {
                    "code": "asset_or_evidence",
                    "message": "Provisioning records may be an information asset or an evidence source and need human classification.",
                }
            ],
        )

    if not candidates:
        add_candidate(
            temporary_id="AST-CAND-001",
            proposed_name="In-Scope Business Asset",
            proposed_description="General placeholder asset candidate derived from the approved case scope.",
            proposed_asset_type="PR",
            proposed_asset_category="unspecified",
            criticality="medium",
            confidence=0.42,
            rationale="The approved case context implies at least one in-scope business asset, but the source text is too general for a more precise fallback classification.",
            source_keys=["scenario", "scope"],
            ambiguity_flags=[
                {
                    "code": "low_specificity",
                    "message": "The fallback parser could not derive a more specific asset and requires human clarification.",
                }
            ],
        )
    return candidates


def _build_rejected_candidates(combined_text: str) -> list[dict[str, Any]]:
    lowered = combined_text.lower()
    rejected: list[dict[str, Any]] = []
    if "mfa" in lowered:
        rejected.append(
            {
                "source_label": "No MFA for remote access",
                "recommended_reclassification": "control_candidate",
                "reason": "The phrase describes a missing security capability and should not be forced into asset creation without a concrete service or platform being named.",
                "confidence": 0.83,
            }
        )
    if "pam" in lowered:
        rejected.append(
            {
                "source_label": "No PAM for privileged admin accounts",
                "recommended_reclassification": "control_candidate",
                "reason": "The phrase describes a missing privileged-access management capability and is better handled as a control or process candidate unless a concrete PAM platform is named.",
                "confidence": 0.81,
            }
        )
    return rejected


def _build_blocking_questions(
    candidates: list[dict[str, Any]],
    strict_mode: bool,
) -> list[dict[str, Any]]:
    questions: list[dict[str, Any]] = []
    if any(item.get("ambiguity_flags") for item in candidates):
        questions.append(
            {
                "question_id": "asset-classification-review",
                "question_text": "Which ambiguous candidate assets should remain assets versus be reclassified as evidence, controls, or vulnerabilities?",
                "reason": "Several candidates describe records, documentation, or account surfaces that cannot be safely forced into Asset creation without human review.",
                "affected_fields": ["candidate_assets", "ambiguous_candidates"],
                "severity": "blocking",
            }
        )
    if strict_mode and all(item.get("confidence", 0.0) < 0.75 for item in candidates):
        questions.append(
            {
                "question_id": "low-confidence-asset-scope",
                "question_text": "Which concrete systems, account estates, or record sets are definitely in scope for the approved case?",
                "reason": "Strict mode prevents low-confidence asset suggestions from being treated as implementation-ready without clarification.",
                "affected_fields": ["candidate_assets"],
                "severity": "blocking",
            }
        )
    return questions


def _build_source_ref(text: str, excerpt: str, ref_id: str) -> dict[str, Any]:
    if excerpt and text:
        lowered_text = text.lower()
        lowered_excerpt = excerpt.lower()
        char_start = lowered_text.find(lowered_excerpt)
        if char_start < 0:
            char_start = 0
        char_end = min(len(text), char_start + len(excerpt))
    else:
        char_start = 0
        char_end = 0
    return {
        "ref_id": ref_id,
        "excerpt": excerpt,
        "char_start": char_start,
        "char_end": char_end,
    }


def _apply_duplicate_detection(draft: dict[str, Any], user, folder: Folder) -> None:
    accessible_ids = _get_visible_asset_ids(user)
    folder_assets = Asset.objects.filter(folder=folder)
    if accessible_ids is not None:
        folder_assets = folder_assets.filter(id__in=accessible_ids)
    folder_assets = list(folder_assets.select_related("folder"))

    duplicate_candidates: list[dict[str, Any]] = []
    for candidate in draft.get("candidate_assets", []):
        matches = _find_candidate_matches(candidate, folder_assets)
        if matches:
            duplicate_candidates.append(
                {
                    "temporary_id": candidate["temporary_id"],
                    "proposed_name": candidate["proposed_name"],
                    "matches": matches,
                    "recommended_human_action": "review_reuse_before_create",
                }
            )
    draft["duplicate_candidates"] = duplicate_candidates


def _get_visible_asset_ids(user):
    if not getattr(user, "is_authenticated", False):
        return None
    try:
        return RoleAssignment.get_accessible_object_ids(
            folder=Folder.get_root_folder(),
            user=user,
            object_type=Asset,
        )[0]
    except Exception:
        return None


def _find_candidate_matches(candidate: dict[str, Any], folder_assets: list[Asset]) -> list[dict[str, Any]]:
    proposed_name = str(candidate.get("proposed_name") or "").strip()
    proposed_ref = str(candidate.get("proposed_reference_id") or "").strip()
    normalized_name = _normalize_token(proposed_name)
    matches: list[dict[str, Any]] = []
    seen_ids: set[str] = set()

    for asset in folder_assets:
        match_type = None
        match_score = 0.0
        if proposed_name and asset.name == proposed_name:
            match_type = "exact_name_same_folder"
            match_score = 0.99
        elif proposed_name and _normalize_token(asset.name) == normalized_name:
            match_type = "normalized_name_same_folder"
            match_score = 0.9
        elif proposed_ref and asset.ref_id and asset.ref_id.strip().lower() == proposed_ref.lower():
            match_type = "reference_id_same_folder"
            match_score = 0.97

        if match_type and str(asset.id) not in seen_ids:
            seen_ids.add(str(asset.id))
            matches.append(
                {
                    "existing_asset_id": asset.id,
                    "existing_name": asset.name,
                    "existing_ref_id": asset.ref_id or None,
                    "existing_type": asset.get_type_display(),
                    "folder_id": asset.folder_id,
                    "folder_name": asset.folder.name,
                    "match_type": match_type,
                    "match_score": match_score,
                    "scope_relevance": "high",
                    "warning": "Potential duplicate within the selected folder.",
                }
            )
    return matches


def _normalize_token(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", value.lower())


def _refresh_ambiguous_candidates(draft: dict[str, Any]) -> None:
    ambiguous_candidates = []
    for candidate in draft.get("candidate_assets", []):
        ambiguity_flags = candidate.get("ambiguity_flags") or []
        if ambiguity_flags:
            ambiguous_candidates.append(
                {
                    "temporary_id": candidate["temporary_id"],
                    "proposed_name": candidate["proposed_name"],
                    "ambiguity_flags": ambiguity_flags,
                    "recommended_actions": [
                        "accept_for_later_commit",
                        "mark_as_evidence_candidate",
                        "mark_as_control_candidate",
                        "mark_as_vulnerability_candidate",
                        "reject",
                        "defer",
                    ],
                }
            )
    draft["ambiguous_candidates"] = ambiguous_candidates


def _refresh_overall_confidence(draft: dict[str, Any]) -> None:
    candidate_assets = draft.get("candidate_assets") or []
    if candidate_assets:
        avg = sum(item.get("confidence", 0.0) for item in candidate_assets) / len(candidate_assets)
    else:
        avg = 0.0
    draft["overall_confidence"] = round(avg, 2)


def _ensure_low_confidence_blocking_question(
    draft: dict[str, Any],
    request_data: dict[str, Any],
) -> None:
    if not request_data.get("strict_mode"):
        return
    if draft.get("overall_confidence", 0.0) >= 0.75:
        return
    if draft.get("blocking_questions"):
        return
    draft.setdefault("blocking_questions", []).append(
        {
            "question_id": "low-confidence-asset-scope",
            "question_text": "Which concrete systems, account estates, or record sets are definitely in scope for the approved case?",
            "reason": "Strict mode requires human confirmation before low-confidence asset suggestions are treated as implementation-ready.",
            "affected_fields": ["candidate_assets"],
            "severity": "blocking",
        }
    )
