from __future__ import annotations

import re
from datetime import date
from pathlib import Path
from typing import Any

from .case_intake_guardrails import (
    CaseIntakeDraftValidationError,
    validate_case_intake_guardrails,
)
from .case_intake_provider import (
    AdvisoryCaseIntakeProvider,
    CaseIntakeProviderError,
    get_case_intake_provider,
)
from .case_intake_serializers import AiCaseIntakeDraftSerializer, DEFAULT_USER_LOCALE


FRAMEWORK_RE = re.compile(r"\b[A-Z]{2,}(?:-\d(?::\d{4})?)\b")


class AiCaseIntakeService:
    def __init__(self, *, base_dir: str | None = None, provider=None):
        self.base_dir = base_dir or str(Path(__file__).resolve().parents[1])
        self.provider = provider

    def build_case_intake_draft(self, request_data: dict[str, Any]) -> dict[str, Any]:
        normalized = _normalize_request_data(request_data)
        provider = self.provider if self.provider is not None else get_case_intake_provider()

        if provider is None:
            draft = build_case_intake_fallback_draft(normalized)
            _annotate_provider_mode(
                draft,
                provider_mode="provider_not_configured_fallback",
                parser_note="provider_mode: provider_not_configured_fallback",
                warning={
                    "code": "provider_not_configured_fallback",
                    "message": "No AI provider is configured; the advisory draft was generated by the deterministic fallback parser.",
                    "affected_fields": ["source_summary", "warnings"],
                    "needs_review": True,
                },
            )
        else:
            try:
                provider_draft = provider.build_case_intake_draft(normalized)
                if isinstance(provider, AdvisoryCaseIntakeProvider):
                    draft = _normalize_provider_draft(provider_draft, normalized)
                else:
                    draft = provider_draft
                _annotate_provider_mode(
                    draft,
                    provider_mode="configured_local_provider",
                    parser_note="provider_mode: configured_local_provider",
                )
            except CaseIntakeProviderError as exc:
                if not exc.allow_fallback:
                    raise
                draft = build_case_intake_fallback_draft(normalized)
                _annotate_provider_mode(
                    draft,
                    provider_mode="local_provider_error_fallback",
                    parser_note="provider_mode: local_provider_error_fallback",
                    warning={
                        "code": "local_provider_error_fallback",
                        "message": exc.detail,
                        "affected_fields": ["source_summary", "warnings"],
                        "needs_review": True,
                    },
                )

        validate_case_intake_guardrails(draft, normalized, enforce_shape=False)

        serializer = AiCaseIntakeDraftSerializer(data=draft)
        if not serializer.is_valid():
            raise CaseIntakeDraftValidationError(
                "ai_draft_validation_failed",
                "Generated advisory draft did not pass contract validation.",
                serializer.errors,
            )

        validated_draft = serializer.data
        validate_case_intake_guardrails(validated_draft, normalized)
        return validated_draft


def build_case_intake_draft(
    request_data: dict[str, Any],
    *,
    base_dir: str | None = None,
    provider=None,
) -> dict[str, Any]:
    service = AiCaseIntakeService(base_dir=base_dir, provider=provider)
    return service.build_case_intake_draft(request_data)


def build_case_intake_fallback_draft(request_data: dict[str, Any]) -> dict[str, Any]:
    scenario_text = request_data.get("scenario_text", "")
    organization_name = request_data.get("organization_hint") or _extract_organization_name(
        scenario_text
    )
    framework_name = request_data.get("preferred_framework") or _extract_framework_name(
        scenario_text
    )
    scope_hint = request_data.get("scope_hint") or _extract_scope_hint(scenario_text)
    deadline = request_data.get("known_deadline") or _assessment_period_end(
        request_data.get("assessment_period")
    )
    trigger = request_data.get("known_trigger") or _extract_trigger(scenario_text)
    locale = request_data.get("user_locale") or DEFAULT_USER_LOCALE
    source_ref = _build_source_ref(scenario_text, scenario_text[:160], "T1")

    warnings = [
        {
            "code": "requirement_nodes_route_mismatch",
            "message": "Frontend uses the 'requirements' key while the backend route remains '/api/requirement-nodes/'.",
            "affected_fields": ["requirement_focus_drafts"],
            "needs_review": True,
        }
    ]
    if request_data.get("_user_locale_fallback_applied"):
        warnings.append(
            {
                "code": "user_locale_fallback",
                "message": "Unsupported locale was normalized to 'en' for the advisory draft.",
                "affected_fields": ["user_locale", "source_summary.detected_language"],
                "needs_review": True,
            }
        )

    blocking_questions = _build_blocking_questions(
        organization_name=organization_name,
        framework_name=framework_name,
        strict_mode=bool(request_data.get("strict_mode", True)),
    )
    overall_confidence = 0.78 if organization_name and framework_name else 0.58

    folder_alias = "draft-folder-domain"
    perimeter_alias = "draft-perimeter"
    framework_dependency = framework_name or "unresolved-framework-candidate"
    candidate_frameworks = []
    if framework_name:
        candidate_frameworks.append(
            {
                "candidate_label": framework_name,
                "stored_library_urn": None,
                "loaded_library_urn_or_id": None,
                "framework_id": None,
                "match_confidence": 0.82,
                "needs_review": True,
                "rationale": "The scenario explicitly names a framework, but no library or framework lookup has been executed.",
            }
        )

    asset_drafts = _build_asset_drafts(
        scenario_text,
        folder_alias=folder_alias,
        source_ref=source_ref,
    )
    applied_control_drafts = _build_applied_control_drafts(
        scenario_text,
        linked_asset_refs=[item["proposed_ref_id"] for item in asset_drafts],
        source_ref=source_ref,
    )
    requirement_focus_drafts = _build_requirement_focus_drafts(
        framework_name,
        source_ref=source_ref,
    )
    evidence_expectation_drafts = _build_evidence_expectation_drafts(
        framework_name,
        source_ref=source_ref,
    )

    organization_label = organization_name or "Unresolved organization"
    perimeter_name = _choose_perimeter_name(organization_label, scope_hint)
    audit_name = _choose_audit_name(organization_label, framework_name)

    return {
        "draft_type": "AiCaseIntakeDraft",
        "schema_version": "0.2.0",
        "source_summary": {
            "detected_language": locale,
            "input_char_count": len(scenario_text),
            "strict_mode_applied": bool(request_data.get("strict_mode", True)),
            "scenario_excerpt": scenario_text[:160],
            "parser_notes": [
                "No GRC objects were created or updated.",
                "Fallback advisory draft generated without executing framework or folder lookups.",
            ],
        },
        "overall_confidence": overall_confidence,
        "needs_human_review": True,
        "blocking_questions": blocking_questions,
        "warnings": warnings,
        "canonical_mappings_used": _build_canonical_mappings(),
        "case_context": {
            "organization_name": organization_name,
            "industry": "fintech" if "fintech" in scenario_text.lower() else None,
            "geography": _extract_geography(scenario_text),
            "regulatory_context": [framework_name] if framework_name else [],
            "assessment_period": _serialize_assessment_period(request_data.get("assessment_period")),
            "deadline": _iso_date(deadline),
            "trigger": trigger,
            "business_objective": _build_business_objective(framework_name, scenario_text),
            "confidence": overall_confidence,
            "rationale": "Context was inferred from the scenario text and optional intake hints without executing any database lookups.",
            "source_text_refs": [source_ref],
            "needs_review": True,
        },
        "framework_resolution": {
            "requested_framework_name": framework_name,
            "canonical_framework_name": framework_name,
            "stored_library_lookup_required": True,
            "loaded_library_lookup_required": True,
            "framework_lookup_required": True,
            "candidate_frameworks": candidate_frameworks,
            "selected_framework_id": None,
            "confidence": 0.8 if framework_name else 0.45,
            "rationale": "Framework resolution remains advisory until StoredLibrary, LoadedLibrary, and Framework lookups confirm the exact artifact.",
            "source_text_refs": [source_ref],
            "needs_review": True,
        },
        "case_setup_draft": {
            "folder_domain_draft": {
                "platform_entity": "Folder",
                "display_label": "Domain",
                "name": organization_name,
                "description": f"Proposed domain for {framework_name or 'GRC'} readiness work covering {scope_hint or 'the scenario scope' }.",
                "content_type": "DO",
                "existing_record_lookup_required": True,
                "suggested_action": "lookup_existing",
                "confidence": 0.75 if organization_name else 0.4,
                "rationale": "The business scenario appears to require a domain-scoped Folder before later perimeter and assessment creation steps.",
                "source_text_refs": [source_ref],
                "needs_review": True,
            },
            "perimeter_draft": {
                "platform_entity": "Perimeter",
                "name": perimeter_name,
                "reference_id": None,
                "description": f"Draft perimeter covering {scope_hint or 'the scope described in the intake scenario'}.",
                "folder_dependency": folder_alias,
                "lifecycle_status_if_known": "in_design" if "launch" in scenario_text.lower() else None,
                "suggested_action": "propose_create",
                "confidence": 0.73,
                "rationale": "A perimeter draft is needed to capture the operational scope before any ComplianceAssessment can be created.",
                "source_text_refs": [source_ref],
                "needs_review": True,
            },
            "compliance_assessment_draft": {
                "platform_entity": "ComplianceAssessment",
                "name": audit_name,
                "reference_id": None,
                "folder_dependency": folder_alias,
                "perimeter_dependency": perimeter_alias,
                "framework_dependency": framework_dependency,
                "assessment_period": _serialize_assessment_period(request_data.get("assessment_period")),
                "status": "planned",
                "auto_requirement_assessment_expected": True,
                "suggested_action": "propose_create",
                "confidence": 0.77 if framework_name else 0.5,
                "rationale": "The scenario describes a readiness review, which maps to a draft ComplianceAssessment once framework, Folder, and Perimeter decisions are confirmed.",
                "source_text_refs": [source_ref],
                "needs_review": True,
            },
            "optional_risk_assessment_draft": None,
            "creation_order": [
                "StoredLibrary lookup",
                "Framework resolution",
                "Folder",
                "Perimeter",
                "ComplianceAssessment",
                "RequirementAssessment follow-up",
            ],
            "dependency_notes": [
                "ComplianceAssessment creation auto-generates RequirementAssessment records.",
                "This draft does not resolve the frontend 'requirements' key versus the backend '/api/requirement-nodes/' route mismatch.",
            ],
            "needs_review": True,
        },
        "asset_drafts": asset_drafts,
        "applied_control_drafts": applied_control_drafts,
        "vulnerability_drafts": [],
        "risk_assessment_draft": None,
        "risk_scenario_drafts": [],
        "requirement_focus_drafts": requirement_focus_drafts,
        "evidence_expectation_drafts": evidence_expectation_drafts,
        "human_review_checklist": [
            {
                "check_id": "confirm-folder-reuse",
                "label": "Confirm whether to reuse an existing Folder or create a new domain Folder.",
                "required": True,
                "related_sections": ["case_setup_draft.folder_domain_draft"],
            },
            {
                "check_id": "confirm-framework-artifact",
                "label": "Confirm the exact StoredLibrary or Framework artifact before any assessment is created.",
                "required": True,
                "related_sections": ["framework_resolution"],
            },
            {
                "check_id": "confirm-perimeter-scope",
                "label": "Confirm the final perimeter name and scope statement before creation.",
                "required": True,
                "related_sections": ["case_setup_draft.perimeter_draft"],
            },
        ],
        "next_system_actions": [
            {
                "action_code": "lookup-framework-candidates",
                "description": "Look up StoredLibrary, LoadedLibrary, and Framework candidates after human confirmation.",
                "requires_human_confirmation": True,
                "may_write_database": False,
            },
            {
                "action_code": "render-review-draft",
                "description": "Render the advisory draft for human review and edits.",
                "requires_human_confirmation": False,
                "may_write_database": False,
            },
        ],
    }


def _normalize_request_data(request_data: dict[str, Any]) -> dict[str, Any]:
    normalized = dict(request_data)
    if normalized.get("known_deadline"):
        normalized["known_deadline"] = _iso_date(normalized["known_deadline"])
    normalized["assessment_period"] = _serialize_assessment_period(normalized.get("assessment_period"))
    normalized["user_locale"] = normalized.get("user_locale") or DEFAULT_USER_LOCALE
    normalized["strict_mode"] = bool(normalized.get("strict_mode", True))
    return normalized


def _annotate_provider_mode(
    draft: dict[str, Any],
    *,
    provider_mode: str,
    parser_note: str,
    warning: dict[str, Any] | None = None,
) -> None:
    source_summary = draft.setdefault("source_summary", {})
    parser_notes = source_summary.setdefault("parser_notes", [])
    if parser_note not in parser_notes:
        parser_notes.append(parser_note)
    source_summary["provider_mode"] = provider_mode
    if warning is not None:
        warnings = draft.setdefault("warnings", [])
        if not any(item.get("code") == warning["code"] for item in warnings if isinstance(item, dict)):
            warnings.append(warning)


def _normalize_provider_draft(
    provider_draft: dict[str, Any],
    normalized_request: dict[str, Any],
) -> dict[str, Any]:
    if not isinstance(provider_draft, dict):
        return build_case_intake_fallback_draft(normalized_request)

    serializer = AiCaseIntakeDraftSerializer(data=provider_draft)
    if serializer.is_valid():
        return provider_draft

    draft = build_case_intake_fallback_draft(normalized_request)
    overall_confidence = provider_draft.get("overall_confidence")
    if isinstance(overall_confidence, (int, float)):
        draft["overall_confidence"] = max(0.0, min(1.0, float(overall_confidence)))

    _annotate_provider_mode(
        draft,
        provider_mode="configured_local_provider",
        parser_note="provider_mode: configured_local_provider_shape_normalized",
        warning={
            "code": "configured_local_provider_shape_normalized",
            "message": "The local AI provider response was normalized to the Step 1 contract-safe draft shape.",
            "affected_fields": ["source_summary", "warnings"],
            "needs_review": True,
        },
    )
    return draft


def _extract_organization_name(scenario_text: str) -> str | None:
    match = re.match(r"^([A-Z][A-Za-z0-9&'\- ]{2,80}?)\s+is\b", scenario_text.strip())
    if match:
        return match.group(1).strip()
    return None


def _extract_framework_name(scenario_text: str) -> str | None:
    match = FRAMEWORK_RE.search(scenario_text)
    return match.group(0).strip() if match else None


def _extract_scope_hint(scenario_text: str) -> str | None:
    lowered = scenario_text.lower()
    if "payment platform" in lowered:
        return "payment platform operations"
    if "iam" in lowered:
        return "identity and access management scope"
    return None


def _extract_trigger(scenario_text: str) -> str | None:
    lowered = scenario_text.lower()
    if "launch" in lowered:
        return "pre-launch readiness review"
    if "regulatory" in lowered:
        return "regulatory readiness"
    return None


def _assessment_period_end(assessment_period: dict[str, Any] | None) -> str | None:
    if isinstance(assessment_period, dict):
        return _iso_date(assessment_period.get("end_date"))
    return None


def _build_business_objective(framework_name: str | None, scenario_text: str) -> str:
    if framework_name:
        return (
            f"Prepare a human-reviewed readiness draft for a {framework_name}-aligned assessment "
            "before any controlled object-creation step."
        )
    return "Prepare a human-reviewed readiness draft before any controlled object-creation step."


def _extract_geography(scenario_text: str) -> list[str]:
    lowered = scenario_text.lower()
    geographies: list[str] = []
    if "saudi" in lowered or "ksa" in lowered:
        geographies.append("Saudi Arabia")
    return geographies


def _build_canonical_mappings() -> list[dict[str, Any]]:
    return [
        {
            "business_term": "Domain",
            "platform_entity": "Folder",
            "api_endpoint": "/api/folders/",
            "note": "Structured output uses Folder for the domain concept.",
        },
        {
            "business_term": "Audit",
            "platform_entity": "ComplianceAssessment",
            "api_endpoint": "/api/compliance-assessments/",
            "note": "Readiness reviews map to ComplianceAssessment rather than a standalone audit entity.",
        },
        {
            "business_term": "Requirement",
            "platform_entity": "RequirementNode",
            "api_endpoint": "/api/requirement-nodes/",
            "note": "The frontend 'requirements' key does not change the canonical backend route.",
        },
    ]


def _build_blocking_questions(
    *,
    organization_name: str | None,
    framework_name: str | None,
    strict_mode: bool,
) -> list[dict[str, Any]]:
    questions: list[dict[str, Any]] = []
    if organization_name:
        questions.append(
            {
                "question_id": "folder-reuse",
                "question_text": f"Should the draft reuse an existing Folder for {organization_name} or propose a new domain Folder?",
                "reason": "The parser cannot safely infer Folder reuse without a lookup and human confirmation.",
                "affected_fields": ["case_setup_draft.folder_domain_draft"],
                "severity": "blocking",
            }
        )
    if framework_name:
        questions.append(
            {
                "question_id": "framework-artifact",
                "question_text": f"Which exact {framework_name} library artifact should be used if multiple StoredLibrary entries match the request?",
                "reason": "The parser cannot resolve StoredLibrary, LoadedLibrary, or Framework ids without an explicit lookup.",
                "affected_fields": ["framework_resolution"],
                "severity": "blocking",
            }
        )
    if strict_mode and not framework_name:
        questions.append(
            {
                "question_id": "missing-framework",
                "question_text": "Which framework or library artifact should anchor this readiness case?",
                "reason": "Strict mode prevents the parser from guessing a framework when the scenario is ambiguous.",
                "affected_fields": ["preferred_framework", "framework_resolution"],
                "severity": "blocking",
            }
        )
    return questions


def _build_asset_drafts(
    scenario_text: str,
    *,
    folder_alias: str,
    source_ref: dict[str, Any],
) -> list[dict[str, Any]]:
    lowered = scenario_text.lower()
    drafts: list[dict[str, Any]] = []
    if "payment platform" in lowered:
        drafts.append(
            {
                "platform_entity": "Asset",
                "proposed_ref_id": "asset-payment-platform",
                "name": "Payment Platform",
                "asset_type": "PR",
                "folder_dependency": folder_alias,
                "perimeter_relevance": "The scenario explicitly references payment platform readiness work.",
                "business_role": "Primary platform supporting payment services.",
                "criticality_if_inferred": "High business criticality due to launch readiness.",
                "suggested_action": "propose_create",
                "confidence": 0.84,
                "rationale": "The scenario explicitly references the payment platform as an in-scope business asset.",
                "source_text_refs": [source_ref],
                "needs_review": True,
            }
        )
    if "iam" in lowered or "identity" in lowered:
        drafts.append(
            {
                "platform_entity": "Asset",
                "proposed_ref_id": "asset-iam-capability",
                "name": "IAM Capability",
                "asset_type": "SP",
                "folder_dependency": folder_alias,
                "perimeter_relevance": "Identity and access management appears relevant to the scenario scope.",
                "business_role": "Supporting capability for access governance and authentication.",
                "criticality_if_inferred": "Medium to high criticality.",
                "suggested_action": "propose_create",
                "confidence": 0.7,
                "rationale": "IAM was explicitly mentioned or strongly implied in the scope language.",
                "source_text_refs": [source_ref],
                "needs_review": True,
            }
        )
    return drafts


def _build_applied_control_drafts(
    scenario_text: str,
    *,
    linked_asset_refs: list[str],
    source_ref: dict[str, Any],
) -> list[dict[str, Any]]:
    lowered = scenario_text.lower()
    drafts: list[dict[str, Any]] = []
    if "evidence" in lowered or "supporting security processes" in lowered:
        drafts.append(
            {
                "platform_entity": "AppliedControl",
                "proposed_ref_id": "control-evidence-readiness",
                "name": "Readiness evidence coordination",
                "control_category": "governance",
                "implementation_status": "to_do",
                "linked_asset_refs": linked_asset_refs,
                "related_requirement_refs_if_inferred": ["ECC-readiness-focus"],
                "control_type": "governance",
                "suggested_action": "defer_until_human_review",
                "confidence": 0.62,
                "rationale": "The scenario implies a need to coordinate readiness evidence and supporting security processes.",
                "source_text_refs": [source_ref],
                "needs_review": True,
            }
        )
    return drafts


def _build_requirement_focus_drafts(
    framework_name: str | None,
    *,
    source_ref: dict[str, Any],
) -> list[dict[str, Any]]:
    if not framework_name:
        return []
    return [
        {
            "platform_entity": "RequirementNode",
            "requirement_reference": "ECC-readiness-focus",
            "focus_reason": f"Prioritize the requirement areas most relevant to the named {framework_name} readiness review after framework lookup and ComplianceAssessment creation.",
            "suggested_action": "defer_until_human_review",
            "confidence": 0.74,
            "rationale": "The framework is named, but exact RequirementNode matches require later framework and library resolution.",
            "source_text_refs": [source_ref],
            "needs_review": True,
        }
    ]


def _build_evidence_expectation_drafts(
    framework_name: str | None,
    *,
    source_ref: dict[str, Any],
) -> list[dict[str, Any]]:
    name = "Launch readiness evidence pack"
    description = "Collect evidence that demonstrates control design, operation, and supporting security processes for the in-scope readiness case."
    if framework_name:
        description = f"Collect evidence that supports {framework_name} readiness expectations for the in-scope assessment."
    return [
        {
            "platform_entity": "Evidence",
            "name": name,
            "description": description,
            "related_requirement_refs_if_inferred": ["ECC-readiness-focus"] if framework_name else [],
            "suggested_action": "defer_until_human_review",
            "confidence": 0.69,
            "rationale": "The scenario indicates that supporting evidence will be required before a readiness review can be completed.",
            "source_text_refs": [source_ref],
            "needs_review": True,
        }
    ]


def _choose_perimeter_name(organization_name: str, scope_hint: str | None) -> str:
    if scope_hint:
        return f"{organization_name} - {scope_hint.title()}"
    return f"{organization_name} - GRC Readiness Scope"


def _choose_audit_name(organization_name: str, framework_name: str | None) -> str:
    if framework_name:
        return f"{organization_name} {framework_name} Readiness Review"
    return f"{organization_name} Readiness Review"


def _build_source_ref(scenario_text: str, excerpt: str, ref_id: str) -> dict[str, Any]:
    excerpt = excerpt.strip()
    char_start = scenario_text.find(excerpt) if excerpt else 0
    if char_start < 0:
        char_start = 0
        excerpt = scenario_text[: min(len(scenario_text), 160)]
    char_end = char_start + len(excerpt)
    return {
        "ref_id": ref_id,
        "excerpt": excerpt,
        "char_start": char_start,
        "char_end": char_end,
    }


def _serialize_assessment_period(assessment_period: Any) -> dict[str, Any] | None:
    if not isinstance(assessment_period, dict):
        return None
    serialized = dict(assessment_period)
    for key in ("start_date", "end_date"):
        serialized[key] = _iso_date(serialized.get(key))
    return serialized


def _iso_date(value: Any) -> str | None:
    if value is None or value == "":
        return None
    if isinstance(value, date):
        return value.isoformat()
    return str(value)