from __future__ import annotations

from pathlib import Path
from typing import Any

from core.models import (
    AppliedControl,
    Asset,
    ComplianceAssessment,
    Framework,
    Perimeter,
    RiskAssessment,
)
from iam.models import Folder, RoleAssignment

from .evidence_finding_suggestion_guardrails import (
    EvidenceFindingSuggestionDraftValidationError,
    validate_evidence_finding_suggestion_guardrails,
)
from .evidence_finding_suggestion_provider import (
    EvidenceFindingSuggestionProviderError,
    get_evidence_finding_suggestion_provider,
)
from .evidence_finding_suggestion_serializers import (
    ADVISORY_NOTICE,
    AiEvidenceFindingSuggestionDraftSerializer,
    DEFAULT_USER_LOCALE,
    DRAFT_TYPE,
    SCHEMA_VERSION,
)


NEXT_ALLOWED_STEPS = [
    "review_evidence_requests",
    "review_audit_questions",
    "review_preliminary_findings",
]

ALLOWED_ITEM_KEYS = {
    "evidence_requests": {
        "temporary_id",
        "title",
        "description",
        "linked_asset_ids",
        "linked_applied_control_ids",
        "rationale",
        "confidence",
        "review_status",
        "ambiguity_flags",
    },
    "audit_questions": {
        "temporary_id",
        "question_text",
        "rationale",
        "linked_asset_ids",
        "linked_applied_control_ids",
        "confidence",
        "review_status",
        "ambiguity_flags",
    },
    "preliminary_findings": {
        "temporary_id",
        "title",
        "summary",
        "severity",
        "rationale",
        "linked_asset_ids",
        "linked_applied_control_ids",
        "related_weaknesses",
        "confidence",
        "review_status",
        "ambiguity_flags",
    },
}

ITEM_TITLE_FIELD = {
    "evidence_requests": "title",
    "audit_questions": "question_text",
    "preliminary_findings": "title",
}

ITEM_ID_PREFIX = {
    "evidence_requests": "EVR-CAND",
    "audit_questions": "AUQ-CAND",
    "preliminary_findings": "FND-CAND",
}


class AiEvidenceFindingSuggestionService:
    def __init__(self, *, base_dir: str | None = None, provider=None):
        self.base_dir = base_dir or str(Path(__file__).resolve().parents[1])
        self.provider = provider

    def build_evidence_finding_suggestion_draft(
        self, request, request_data: dict[str, Any]
    ) -> dict[str, Any]:
        normalized = _normalize_request_data(request_data)
        context = _resolve_context(request.user, normalized)
        resolved_assets = _resolve_asset_references(
            request.user, normalized["asset_references"], context["folder"]
        )
        resolved_controls = _resolve_applied_control_references(
            request.user, normalized["applied_control_references"], context["folder"]
        )

        provider = (
            self.provider
            if self.provider is not None
            else get_evidence_finding_suggestion_provider()
        )

        if provider is None:
            draft = build_evidence_finding_suggestion_fallback_draft(
                normalized, context, resolved_assets, resolved_controls
            )
            _annotate_provider_mode(
                draft,
                provider_mode="provider_not_configured_fallback",
                warning={
                    "code": "provider_not_configured_fallback",
                    "message": "No AI provider is configured; the advisory evidence/finding suggestion draft was generated by the deterministic fallback.",
                    "affected_fields": ["evidence_requests", "audit_questions", "preliminary_findings"],
                    "needs_review": True,
                },
            )
        else:
            try:
                draft = provider.build_evidence_finding_suggestion_draft(normalized)
                _annotate_provider_mode(draft, provider_mode="configured_local_provider")
            except EvidenceFindingSuggestionProviderError as exc:
                if not exc.allow_fallback:
                    raise
                draft = build_evidence_finding_suggestion_fallback_draft(
                    normalized, context, resolved_assets, resolved_controls
                )
                _annotate_provider_mode(
                    draft,
                    provider_mode="local_provider_error_fallback",
                    warning={
                        "code": "local_provider_error_fallback",
                        "message": exc.detail,
                        "affected_fields": ["evidence_requests", "audit_questions", "preliminary_findings"],
                        "needs_review": True,
                    },
                )

        _enrich_draft(draft, normalized, context, resolved_assets, resolved_controls)

        allowed_asset_ids = {str(item["instance"].id) for item in resolved_assets}
        allowed_control_ids = {str(item["instance"].id) for item in resolved_controls}
        validate_evidence_finding_suggestion_guardrails(
            draft,
            allowed_asset_ids=allowed_asset_ids,
            allowed_applied_control_ids=allowed_control_ids,
            enforce_shape=False,
        )

        serializer = AiEvidenceFindingSuggestionDraftSerializer(data=draft)
        if not serializer.is_valid():
            raise EvidenceFindingSuggestionDraftValidationError(
                "ai_evidence_finding_suggestion_draft_validation_failed",
                "Generated advisory evidence/finding suggestion draft did not pass contract validation.",
                serializer.errors,
            )

        validated_draft = serializer.data
        validate_evidence_finding_suggestion_guardrails(
            validated_draft,
            allowed_asset_ids=allowed_asset_ids,
            allowed_applied_control_ids=allowed_control_ids,
            enforce_shape=True,
        )
        return validated_draft


def build_evidence_finding_suggestion_draft(
    request,
    request_data: dict[str, Any],
    *,
    base_dir: str | None = None,
    provider=None,
) -> dict[str, Any]:
    service = AiEvidenceFindingSuggestionService(base_dir=base_dir, provider=provider)
    return service.build_evidence_finding_suggestion_draft(request, request_data)


def build_evidence_finding_suggestion_fallback_draft(
    request_data: dict[str, Any],
    context: dict[str, Any],
    resolved_assets: list[dict[str, Any]],
    resolved_controls: list[dict[str, Any]],
) -> dict[str, Any]:
    asset_ids = [str(item["instance"].id) for item in resolved_assets]
    control_ids = [str(item["instance"].id) for item in resolved_controls]
    known_weaknesses = request_data.get("known_weaknesses") or []

    evidence_requests: list[dict[str, Any]] = []
    audit_questions: list[dict[str, Any]] = []
    preliminary_findings: list[dict[str, Any]] = []

    for index, item in enumerate(resolved_controls, start=1):
        control = item["instance"]
        evidence_requests.append(
            {
                "temporary_id": f"EVR-CAND-{index:03d}",
                "title": f"Evidence request for {control.name}",
                "description": f"Request implementation and operating evidence for the applied control '{control.name}'.",
                "linked_asset_ids": list(asset_ids),
                "linked_applied_control_ids": [str(control.id)],
                "rationale": "Evidence is needed to demonstrate the committed applied control is implemented and operating.",
                "confidence": 0.7,
                "review_status": "pending_review",
                "ambiguity_flags": [],
            }
        )
        audit_questions.append(
            {
                "temporary_id": f"AUQ-CAND-{index:03d}",
                "question_text": f"How is the applied control '{control.name}' implemented, operated, and monitored for the approved scope?",
                "rationale": "Audit confirmation is required before any finding is drafted for this control.",
                "linked_asset_ids": list(asset_ids),
                "linked_applied_control_ids": [str(control.id)],
                "confidence": 0.7,
                "review_status": "pending_review",
                "ambiguity_flags": [],
            }
        )

    for index, weakness in enumerate(known_weaknesses, start=1):
        preliminary_findings.append(
            {
                "temporary_id": f"FND-CAND-{index:03d}",
                "title": f"Preliminary finding draft: {weakness}"[:200],
                "summary": f"Advisory draft finding based on the reported weakness: {weakness}.",
                "severity": None,
                "rationale": "Derived from a reported weakness; requires human confirmation and audit evidence before becoming a finding.",
                "linked_asset_ids": list(asset_ids),
                "linked_applied_control_ids": list(control_ids),
                "related_weaknesses": [weakness],
                "confidence": 0.6,
                "review_status": "pending_review",
                "ambiguity_flags": [],
            }
        )

    if not preliminary_findings and resolved_controls:
        control = resolved_controls[0]["instance"]
        preliminary_findings.append(
            {
                "temporary_id": "FND-CAND-001",
                "title": f"Preliminary finding draft for {control.name}"[:200],
                "summary": "Advisory draft finding pending audit evidence for the committed applied control.",
                "severity": None,
                "rationale": "Placeholder advisory finding draft; requires human confirmation and audit evidence.",
                "linked_asset_ids": list(asset_ids),
                "linked_applied_control_ids": [str(control.id)],
                "related_weaknesses": [],
                "confidence": 0.55,
                "review_status": "pending_review",
                "ambiguity_flags": [],
            }
        )

    return {
        "draft_type": DRAFT_TYPE,
        "schema_version": SCHEMA_VERSION,
        "advisory_notice": ADVISORY_NOTICE,
        "no_write": True,
        "provider_mode": "provider_not_configured_fallback",
        "evidence_requests": evidence_requests,
        "audit_questions": audit_questions,
        "preliminary_findings": preliminary_findings,
        "warnings": [],
        "needs_human_review": True,
        "review_status": "pending_review",
        "next_allowed_steps": list(NEXT_ALLOWED_STEPS),
    }


def _normalize_request_data(request_data: dict[str, Any]) -> dict[str, Any]:
    normalized = dict(request_data)
    normalized["user_locale"] = normalized.get("user_locale") or DEFAULT_USER_LOCALE
    normalized["strict_mode"] = bool(normalized.get("strict_mode", True))
    normalized["known_weaknesses"] = list(normalized.get("known_weaknesses") or [])
    return normalized


def _annotate_provider_mode(
    draft: dict[str, Any],
    *,
    provider_mode: str,
    warning: dict[str, Any] | None = None,
) -> None:
    draft["provider_mode"] = provider_mode
    source_summary = draft.setdefault("source_summary", {})
    source_summary["provider_mode"] = provider_mode
    if warning is not None:
        warnings = draft.setdefault("warnings", [])
        if not any(
            isinstance(item, dict) and item.get("code") == warning["code"] for item in warnings
        ):
            warnings.append(warning)


def _resolve_context(user, request_data: dict[str, Any]) -> dict[str, Any]:
    reference = request_data.get("case_setup_reference") or {}
    folder = _get_object_or_error(Folder, reference["folder_id"], "case_setup_reference.folder_id")

    perimeter = None
    if reference.get("perimeter_id"):
        perimeter = _get_object_or_error(
            Perimeter, reference["perimeter_id"], "case_setup_reference.perimeter_id"
        )

    compliance_assessment = None
    if reference.get("compliance_assessment_id"):
        compliance_assessment = _get_object_or_error(
            ComplianceAssessment,
            reference["compliance_assessment_id"],
            "case_setup_reference.compliance_assessment_id",
        )

    risk_assessment = None
    if reference.get("risk_assessment_id"):
        risk_assessment = _get_object_or_error(
            RiskAssessment,
            reference["risk_assessment_id"],
            "case_setup_reference.risk_assessment_id",
        )

    framework = None
    framework_id = request_data.get("selected_framework_id") or reference.get("selected_framework_id")
    if framework_id:
        framework = _get_object_or_error(Framework, framework_id, "selected_framework_id")

    _assert_visible_to_user(user, folder, "case_setup_reference.folder_id")
    if perimeter is not None:
        _assert_visible_to_user(user, perimeter, "case_setup_reference.perimeter_id")
    if compliance_assessment is not None:
        _assert_visible_to_user(
            user, compliance_assessment, "case_setup_reference.compliance_assessment_id"
        )
    if risk_assessment is not None:
        _assert_visible_to_user(user, risk_assessment, "case_setup_reference.risk_assessment_id")
    if framework is not None:
        _assert_visible_to_user(user, framework, "selected_framework_id")

    errors = {}
    if perimeter is not None and perimeter.folder_id and str(perimeter.folder_id) != str(folder.id):
        errors["case_setup_reference"] = [
            "The selected Perimeter does not belong to case_setup_reference.folder_id."
        ]
    if compliance_assessment is not None and compliance_assessment.folder_id and str(
        compliance_assessment.folder_id
    ) != str(folder.id):
        errors["case_setup_reference"] = [
            "The selected ComplianceAssessment does not belong to case_setup_reference.folder_id."
        ]
    if risk_assessment is not None and risk_assessment.folder_id and str(
        risk_assessment.folder_id
    ) != str(folder.id):
        errors["case_setup_reference"] = [
            "The selected RiskAssessment does not belong to case_setup_reference.folder_id."
        ]
    if errors:
        raise EvidenceFindingSuggestionDraftValidationError(
            "ai_evidence_finding_suggestion_context_invalid",
            "The Step 5A request contains inconsistent case setup references.",
            errors,
        )

    return {
        "folder": folder,
        "perimeter": perimeter,
        "compliance_assessment": compliance_assessment,
        "risk_assessment": risk_assessment,
        "framework": framework,
    }


def _resolve_asset_references(
    user, asset_references: list[dict[str, Any]], folder: Folder
) -> list[dict[str, Any]]:
    resolved: list[dict[str, Any]] = []
    errors: dict[str, list[str]] = {}

    for index, reference in enumerate(asset_references):
        asset = Asset.objects.filter(id=reference["asset_id"]).select_related("folder").first()
        field_name = f"asset_references[{index}].asset_id"
        if asset is None:
            errors[field_name] = ["No Asset record was found for the supplied id."]
            continue
        _assert_visible_to_user(user, asset, field_name)
        if str(asset.folder_id) != str(folder.id):
            errors[field_name] = ["The referenced Asset does not belong to case_setup_reference.folder_id."]
            continue
        resolved.append({"instance": asset, "reference": reference})

    if errors:
        raise EvidenceFindingSuggestionDraftValidationError(
            "ai_evidence_finding_suggestion_asset_references_invalid",
            "The Step 5A request contains invalid asset references.",
            errors,
        )
    return resolved


def _resolve_applied_control_references(
    user, applied_control_references: list[dict[str, Any]], folder: Folder
) -> list[dict[str, Any]]:
    resolved: list[dict[str, Any]] = []
    errors: dict[str, list[str]] = {}

    for index, reference in enumerate(applied_control_references):
        control = (
            AppliedControl.objects.filter(id=reference["applied_control_id"])
            .select_related("folder")
            .first()
        )
        field_name = f"applied_control_references[{index}].applied_control_id"
        if control is None:
            errors[field_name] = ["No AppliedControl record was found for the supplied id."]
            continue
        _assert_visible_to_user(user, control, field_name)
        if str(control.folder_id) != str(folder.id):
            errors[field_name] = [
                "The referenced AppliedControl does not belong to case_setup_reference.folder_id."
            ]
            continue
        resolved.append({"instance": control, "reference": reference})

    if errors:
        raise EvidenceFindingSuggestionDraftValidationError(
            "ai_evidence_finding_suggestion_applied_control_references_invalid",
            "The Step 5A request contains invalid applied control references.",
            errors,
        )
    return resolved


def _get_object_or_error(model_class, object_id, field_name: str):
    instance = model_class.objects.filter(id=object_id).first()
    if instance is None:
        raise EvidenceFindingSuggestionDraftValidationError(
            "ai_evidence_finding_suggestion_context_not_found",
            f"{field_name} could not be resolved.",
            {field_name: [f"No {model_class.__name__} record was found for the supplied id."]},
        )
    return instance


def _assert_visible_to_user(user, instance, field_name: str) -> None:
    if not getattr(user, "is_authenticated", False):
        return
    try:
        visible_ids = RoleAssignment.get_accessible_object_ids(
            folder=Folder.get_root_folder(),
            user=user,
            object_type=instance.__class__,
        )[0]
    except Exception:
        return
    if str(instance.id) not in {str(item_id) for item_id in visible_ids}:
        raise EvidenceFindingSuggestionDraftValidationError(
            "ai_evidence_finding_suggestion_permission_denied",
            f"{field_name} is not visible to the current user.",
            {field_name: ["You do not have permission to access this object."]},
        )


def _enrich_draft(
    draft: dict[str, Any],
    request_data: dict[str, Any],
    context: dict[str, Any],
    resolved_assets: list[dict[str, Any]],
    resolved_controls: list[dict[str, Any]],
) -> None:
    draft.setdefault("draft_type", DRAFT_TYPE)
    draft.setdefault("schema_version", SCHEMA_VERSION)
    draft.setdefault("advisory_notice", ADVISORY_NOTICE)
    draft["advisory_notice"] = ADVISORY_NOTICE
    draft["no_write"] = True
    draft["needs_human_review"] = True
    draft["review_status"] = "pending_review"
    draft.setdefault("warnings", [])
    draft.setdefault("provider_mode", "configured_local_provider")
    draft.setdefault("next_allowed_steps", list(NEXT_ALLOWED_STEPS))

    approved_asset_ids = [str(item["instance"].id) for item in resolved_assets]
    approved_control_ids = [str(item["instance"].id) for item in resolved_controls]

    for group_name in ("evidence_requests", "audit_questions", "preliminary_findings"):
        items = draft.get(group_name)
        if not isinstance(items, list):
            draft[group_name] = []
            continue
        draft[group_name] = [
            _enrich_item(group_name, index, item, approved_asset_ids, approved_control_ids)
            for index, item in enumerate(items, start=1)
            if isinstance(item, dict)
        ]

    _inject_source_summary(draft, request_data, context, resolved_assets, resolved_controls)
    _refresh_overall_confidence(draft)


def _enrich_item(
    group_name: str,
    index: int,
    item: dict[str, Any],
    approved_asset_ids: list[str],
    approved_control_ids: list[str],
) -> dict[str, Any]:
    allowed_keys = ALLOWED_ITEM_KEYS[group_name]
    cleaned = {key: value for key, value in item.items() if key in allowed_keys}

    cleaned.setdefault("temporary_id", f"{ITEM_ID_PREFIX[group_name]}-{index:03d}")

    title_field = ITEM_TITLE_FIELD[group_name]
    if not cleaned.get(title_field):
        cleaned[title_field] = f"{group_name[:-1].replace('_', ' ').title()} candidate {index}"

    if group_name == "preliminary_findings":
        cleaned.setdefault("summary", cleaned.get("summary") or "")
        cleaned.setdefault("severity", None)
        cleaned.setdefault("related_weaknesses", [])
    if group_name == "evidence_requests":
        cleaned.setdefault("description", cleaned.get("description") or "")

    cleaned.setdefault("rationale", "Advisory Step 5A suggestion pending human review.")
    cleaned["review_status"] = "pending_review"
    cleaned["ambiguity_flags"] = _normalize_ambiguity_flags(cleaned.get("ambiguity_flags"))

    confidence = cleaned.get("confidence")
    if not isinstance(confidence, (int, float)):
        confidence = 0.7
    cleaned["confidence"] = max(0.0, min(1.0, float(confidence)))

    linked_asset_ids = [str(asset_id) for asset_id in cleaned.get("linked_asset_ids") or []]
    linked_asset_ids = [asset_id for asset_id in linked_asset_ids if asset_id in approved_asset_ids]
    if not linked_asset_ids:
        linked_asset_ids = list(approved_asset_ids)
    cleaned["linked_asset_ids"] = linked_asset_ids

    linked_control_ids = [str(cid) for cid in cleaned.get("linked_applied_control_ids") or []]
    linked_control_ids = [cid for cid in linked_control_ids if cid in approved_control_ids]
    if not linked_control_ids:
        linked_control_ids = list(approved_control_ids)
    cleaned["linked_applied_control_ids"] = linked_control_ids

    return cleaned


def _normalize_ambiguity_flags(value: Any) -> list[dict[str, str]]:
    """Coerce provider-supplied ambiguity flags into the {code, message} contract.

    Local providers sometimes return ambiguity_flags as bare strings. Normalize each
    entry before serializer validation so a string becomes an object, a dict is reduced
    to its code/message, and anything else is dropped.
    """
    if not isinstance(value, list):
        return []

    normalized: list[dict[str, str]] = []
    for flag in value:
        if isinstance(flag, str):
            message = flag.strip()
            if message:
                normalized.append({"code": "provider_ambiguity", "message": message})
        elif isinstance(flag, dict):
            code = str(flag.get("code") or "provider_ambiguity").strip() or "provider_ambiguity"
            message = flag.get("message")
            if not isinstance(message, str) or not message.strip():
                message = str(flag.get("code") or "Ambiguity flagged by provider.")
            normalized.append({"code": code, "message": message.strip()})
        # Non-string, non-dict entries are dropped (treated as invalid).
    return normalized


def _inject_source_summary(
    draft: dict[str, Any],
    request_data: dict[str, Any],
    context: dict[str, Any],
    resolved_assets: list[dict[str, Any]],
    resolved_controls: list[dict[str, Any]],
) -> None:
    scenario_text = request_data.get("scenario_text") or ""
    scope_summary = request_data.get("scope_summary") or ""
    source_summary = draft.setdefault("source_summary", {})
    source_summary["detected_language"] = request_data.get("user_locale", DEFAULT_USER_LOCALE)
    source_summary["input_char_count"] = len(scenario_text)
    source_summary["strict_mode_applied"] = bool(request_data.get("strict_mode", True))
    source_summary["scenario_excerpt"] = (scenario_text or scope_summary)[:160]
    source_summary["provider_mode"] = draft.get("provider_mode", "configured_local_provider")
    source_summary["folder_id"] = context["folder"].id
    source_summary["perimeter_id"] = getattr(context.get("perimeter"), "id", None)
    source_summary["compliance_assessment_id"] = getattr(
        context.get("compliance_assessment"), "id", None
    )
    source_summary["risk_assessment_id"] = getattr(context.get("risk_assessment"), "id", None)
    source_summary["selected_framework_id"] = getattr(context.get("framework"), "id", None)
    source_summary["asset_count"] = len(resolved_assets)
    source_summary["applied_control_count"] = len(resolved_controls)
    parser_notes = source_summary.setdefault("parser_notes", [])
    note = "Step 5A remained advisory-only and performed zero database writes."
    if note not in parser_notes:
        parser_notes.append(note)


def _refresh_overall_confidence(draft: dict[str, Any]) -> None:
    scores: list[float] = []
    for group_name in ("evidence_requests", "audit_questions", "preliminary_findings"):
        for item in draft.get(group_name, []):
            score = item.get("confidence")
            if isinstance(score, (int, float)):
                scores.append(float(score))
    draft["overall_confidence"] = round(sum(scores) / len(scores), 2) if scores else 0.0
